/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _GPIO_REGS_H_
#define _GPIO_REGS_H_

// Block name           : gpio
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define GPIO_OUT_OFFS 0
#define GPIO_OUT_XOR_OFFS 4
#define GPIO_OUT_SET_OFFS 8
#define GPIO_OUT_CLR_OFFS 12
#define GPIO_OEN_OFFS 16
#define GPIO_OEN_XOR_OFFS 20
#define GPIO_OEN_SET_OFFS 24
#define GPIO_OEN_CLR_OFFS 28
#define GPIO_IN_OFFS 32
#define GPIO_FSEL_OFFS 36

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t out;
	volatile uint32_t out_xor;
	volatile uint32_t out_set;
	volatile uint32_t out_clr;
	volatile uint32_t oen;
	volatile uint32_t oen_xor;
	volatile uint32_t oen_set;
	volatile uint32_t oen_clr;
	volatile uint32_t in;
	volatile uint32_t fsel;
} gpio_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     OUT                                      *
*******************************************************************************/

// Field: OUT  Access: RWV
// Reset: 0x0
// Write output levels for GPIOS, or read to get current output levels
#define GPIO_OUT_LSB  0
#define GPIO_OUT_BITS 8
#define GPIO_OUT_MASK 0xff

/*******************************************************************************
*                                   OUT_XOR                                    *
*******************************************************************************/

// Field: OUT_XOR  Access: RWV
// Reset: 0x0
// XOR bits in output levels for GPIOS, or read to get current output levels
#define GPIO_OUT_XOR_LSB  0
#define GPIO_OUT_XOR_BITS 8
#define GPIO_OUT_XOR_MASK 0xff

/*******************************************************************************
*                                   OUT_SET                                    *
*******************************************************************************/

// Field: OUT_SET  Access: RWV
// Reset: 0x0
// OR bits in output levels for GPIOS, or read to get current output levels
#define GPIO_OUT_SET_LSB  0
#define GPIO_OUT_SET_BITS 8
#define GPIO_OUT_SET_MASK 0xff

/*******************************************************************************
*                                   OUT_CLR                                    *
*******************************************************************************/

// Field: OUT_CLR  Access: RWV
// Reset: 0x0
// Mask bits (AND with complement) in output levels for GPIOS, or read to get
// current output levels
#define GPIO_OUT_CLR_LSB  0
#define GPIO_OUT_CLR_BITS 8
#define GPIO_OUT_CLR_MASK 0xff

/*******************************************************************************
*                                     OEN                                      *
*******************************************************************************/

// Field: OEN  Access: RWV
// Reset: 0x0
// Write output enables (active high) for GPIOS, or read to get current output
// enables
#define GPIO_OEN_LSB  0
#define GPIO_OEN_BITS 8
#define GPIO_OEN_MASK 0xff

/*******************************************************************************
*                                   OEN_XOR                                    *
*******************************************************************************/

// Field: OEN_XOR  Access: RWV
// Reset: 0x0
// XOR bits in output enables for GPIOS, or read to get current output enables
#define GPIO_OEN_XOR_LSB  0
#define GPIO_OEN_XOR_BITS 8
#define GPIO_OEN_XOR_MASK 0xff

/*******************************************************************************
*                                   OEN_SET                                    *
*******************************************************************************/

// Field: OEN_SET  Access: RWV
// Reset: 0x0
// OR bits in output enables for GPIOS, or read to get current output enables
#define GPIO_OEN_SET_LSB  0
#define GPIO_OEN_SET_BITS 8
#define GPIO_OEN_SET_MASK 0xff

/*******************************************************************************
*                                   OEN_CLR                                    *
*******************************************************************************/

// Field: OEN_CLR  Access: RWV
// Reset: 0x0
// Mask bits (AND with complement) in output enables for GPIOS, or read to get
// current output enables
#define GPIO_OEN_CLR_LSB  0
#define GPIO_OEN_CLR_BITS 8
#define GPIO_OEN_CLR_MASK 0xff

/*******************************************************************************
*                                      IN                                      *
*******************************************************************************/

// Field: IN  Access: ROV
// Reset: 0x0
// Read pad inputs (always synchronised)
#define GPIO_IN_LSB  0
#define GPIO_IN_BITS 8
#define GPIO_IN_MASK 0xff

/*******************************************************************************
*                                     FSEL                                     *
*******************************************************************************/

// Field: FSEL  Access: RW
// Reset: 0x0
// Enable GPIO alternate functions. 0 = software-controlled, 1 = alternate.
#define GPIO_FSEL_LSB  0
#define GPIO_FSEL_BITS 8
#define GPIO_FSEL_MASK 0xff

#endif // _GPIO_REGS_H_
