/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : gpio
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module gpio_regs (
	input wire         clk,
	input wire         rst_n,
	
	// APB Port
	input  wire        apbs_psel,
	input  wire        apbs_penable,
	input  wire        apbs_pwrite,
	input  wire [15:0] apbs_paddr,
	input  wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire        apbs_pready,
	output wire        apbs_pslverr,
	
	// Register interfaces
	input  wire [12:0] out_i,
	output reg  [12:0] out_o,
	output reg         out_wen,
	input  wire [12:0] out_xor_i,
	output reg  [12:0] out_xor_o,
	output reg         out_xor_wen,
	input  wire [12:0] out_set_i,
	output reg  [12:0] out_set_o,
	output reg         out_set_wen,
	input  wire [12:0] out_clr_i,
	output reg  [12:0] out_clr_o,
	output reg         out_clr_wen,
	input  wire [12:0] oen_i,
	output reg  [12:0] oen_o,
	output reg         oen_wen,
	input  wire [12:0] oen_xor_i,
	output reg  [12:0] oen_xor_o,
	output reg         oen_xor_wen,
	input  wire [12:0] oen_set_i,
	output reg  [12:0] oen_set_o,
	output reg         oen_set_wen,
	input  wire [12:0] oen_clr_i,
	output reg  [12:0] oen_clr_o,
	output reg         oen_clr_wen,
	input  wire [12:0] fsel_i,
	output reg  [12:0] fsel_o,
	output reg         fsel_wen,
	input  wire [12:0] fsel_xor_i,
	output reg  [12:0] fsel_xor_o,
	output reg         fsel_xor_wen,
	input  wire [12:0] fsel_set_i,
	output reg  [12:0] fsel_set_o,
	output reg         fsel_set_wen,
	input  wire [12:0] fsel_clr_i,
	output reg  [12:0] fsel_clr_o,
	output reg         fsel_clr_wen,
	input  wire [12:0] in_i
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg  [31:0] rdata;
reg         wen;
reg         ren;
reg  [15:0] addr;

assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_OUT = 0;
localparam ADDR_OUT_XOR = 4;
localparam ADDR_OUT_SET = 8;
localparam ADDR_OUT_CLR = 12;
localparam ADDR_OEN = 16;
localparam ADDR_OEN_XOR = 20;
localparam ADDR_OEN_SET = 24;
localparam ADDR_OEN_CLR = 28;
localparam ADDR_FSEL = 32;
localparam ADDR_FSEL_XOR = 36;
localparam ADDR_FSEL_SET = 40;
localparam ADDR_FSEL_CLR = 44;
localparam ADDR_IN = 48;

wire __out_wen = wen && addr == ADDR_OUT;
wire __out_ren = ren && addr == ADDR_OUT;
wire __out_xor_wen = wen && addr == ADDR_OUT_XOR;
wire __out_xor_ren = ren && addr == ADDR_OUT_XOR;
wire __out_set_wen = wen && addr == ADDR_OUT_SET;
wire __out_set_ren = ren && addr == ADDR_OUT_SET;
wire __out_clr_wen = wen && addr == ADDR_OUT_CLR;
wire __out_clr_ren = ren && addr == ADDR_OUT_CLR;
wire __oen_wen = wen && addr == ADDR_OEN;
wire __oen_ren = ren && addr == ADDR_OEN;
wire __oen_xor_wen = wen && addr == ADDR_OEN_XOR;
wire __oen_xor_ren = ren && addr == ADDR_OEN_XOR;
wire __oen_set_wen = wen && addr == ADDR_OEN_SET;
wire __oen_set_ren = ren && addr == ADDR_OEN_SET;
wire __oen_clr_wen = wen && addr == ADDR_OEN_CLR;
wire __oen_clr_ren = ren && addr == ADDR_OEN_CLR;
wire __fsel_wen = wen && addr == ADDR_FSEL;
wire __fsel_ren = ren && addr == ADDR_FSEL;
wire __fsel_xor_wen = wen && addr == ADDR_FSEL_XOR;
wire __fsel_xor_ren = ren && addr == ADDR_FSEL_XOR;
wire __fsel_set_wen = wen && addr == ADDR_FSEL_SET;
wire __fsel_set_ren = ren && addr == ADDR_FSEL_SET;
wire __fsel_clr_wen = wen && addr == ADDR_FSEL_CLR;
wire __fsel_clr_ren = ren && addr == ADDR_FSEL_CLR;
wire __in_wen = wen && addr == ADDR_IN;
wire __in_ren = ren && addr == ADDR_IN;

wire [12:0] out_wdata = wdata[12:0];
wire [12:0] out_rdata;
wire [31:0] __out_rdata = {19'h0, out_rdata};
assign out_rdata = out_i;

wire [12:0] out_xor_wdata = wdata[12:0];
wire [12:0] out_xor_rdata;
wire [31:0] __out_xor_rdata = {19'h0, out_xor_rdata};
assign out_xor_rdata = out_xor_i;

wire [12:0] out_set_wdata = wdata[12:0];
wire [12:0] out_set_rdata;
wire [31:0] __out_set_rdata = {19'h0, out_set_rdata};
assign out_set_rdata = out_set_i;

wire [12:0] out_clr_wdata = wdata[12:0];
wire [12:0] out_clr_rdata;
wire [31:0] __out_clr_rdata = {19'h0, out_clr_rdata};
assign out_clr_rdata = out_clr_i;

wire [12:0] oen_wdata = wdata[12:0];
wire [12:0] oen_rdata;
wire [31:0] __oen_rdata = {19'h0, oen_rdata};
assign oen_rdata = oen_i;

wire [12:0] oen_xor_wdata = wdata[12:0];
wire [12:0] oen_xor_rdata;
wire [31:0] __oen_xor_rdata = {19'h0, oen_xor_rdata};
assign oen_xor_rdata = oen_xor_i;

wire [12:0] oen_set_wdata = wdata[12:0];
wire [12:0] oen_set_rdata;
wire [31:0] __oen_set_rdata = {19'h0, oen_set_rdata};
assign oen_set_rdata = oen_set_i;

wire [12:0] oen_clr_wdata = wdata[12:0];
wire [12:0] oen_clr_rdata;
wire [31:0] __oen_clr_rdata = {19'h0, oen_clr_rdata};
assign oen_clr_rdata = oen_clr_i;

wire [12:0] fsel_wdata = wdata[12:0];
wire [12:0] fsel_rdata;
wire [31:0] __fsel_rdata = {19'h0, fsel_rdata};
assign fsel_rdata = fsel_i;

wire [12:0] fsel_xor_wdata = wdata[12:0];
wire [12:0] fsel_xor_rdata;
wire [31:0] __fsel_xor_rdata = {19'h0, fsel_xor_rdata};
assign fsel_xor_rdata = fsel_xor_i;

wire [12:0] fsel_set_wdata = wdata[12:0];
wire [12:0] fsel_set_rdata;
wire [31:0] __fsel_set_rdata = {19'h0, fsel_set_rdata};
assign fsel_set_rdata = fsel_set_i;

wire [12:0] fsel_clr_wdata = wdata[12:0];
wire [12:0] fsel_clr_rdata;
wire [31:0] __fsel_clr_rdata = {19'h0, fsel_clr_rdata};
assign fsel_clr_rdata = fsel_clr_i;

wire [12:0] in_wdata = wdata[12:0];
wire [12:0] in_rdata;
wire [31:0] __in_rdata = {19'h0, in_rdata};
assign in_rdata = in_i;

always @ (*) begin
	case (addr)
		ADDR_OUT: rdata = __out_rdata;
		ADDR_OUT_XOR: rdata = __out_xor_rdata;
		ADDR_OUT_SET: rdata = __out_set_rdata;
		ADDR_OUT_CLR: rdata = __out_clr_rdata;
		ADDR_OEN: rdata = __oen_rdata;
		ADDR_OEN_XOR: rdata = __oen_xor_rdata;
		ADDR_OEN_SET: rdata = __oen_set_rdata;
		ADDR_OEN_CLR: rdata = __oen_clr_rdata;
		ADDR_FSEL: rdata = __fsel_rdata;
		ADDR_FSEL_XOR: rdata = __fsel_xor_rdata;
		ADDR_FSEL_SET: rdata = __fsel_set_rdata;
		ADDR_FSEL_CLR: rdata = __fsel_clr_rdata;
		ADDR_IN: rdata = __in_rdata;
		default: rdata = 32'h0;
	endcase
	out_wen = __out_wen;
	out_o = out_wdata;
	out_xor_wen = __out_xor_wen;
	out_xor_o = out_xor_wdata;
	out_set_wen = __out_set_wen;
	out_set_o = out_set_wdata;
	out_clr_wen = __out_clr_wen;
	out_clr_o = out_clr_wdata;
	oen_wen = __oen_wen;
	oen_o = oen_wdata;
	oen_xor_wen = __oen_xor_wen;
	oen_xor_o = oen_xor_wdata;
	oen_set_wen = __oen_set_wen;
	oen_set_o = oen_set_wdata;
	oen_clr_wen = __oen_clr_wen;
	oen_clr_o = oen_clr_wdata;
	fsel_wen = __fsel_wen;
	fsel_o = fsel_wdata;
	fsel_xor_wen = __fsel_xor_wen;
	fsel_xor_o = fsel_xor_wdata;
	fsel_set_wen = __fsel_set_wen;
	fsel_set_o = fsel_set_wdata;
	fsel_clr_wen = __fsel_clr_wen;
	fsel_clr_o = fsel_clr_wdata;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 16'd0;
	end else begin
		wen <= apbs_psel && !apbs_penable &&  apbs_pwrite;
		ren <= apbs_psel && !apbs_penable && !apbs_pwrite;
		if (apbs_psel && !apbs_penable) addr <= apbs_paddr & 16'h3c;
	end
end

endmodule
