/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _APU_IPC_REGS_H_
#define _APU_IPC_REGS_H_

// Block name           : apu_ipc
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

#define APU_IPC_START_APU_OFFS 0
#define APU_IPC_SOFTIRQ_SET_OFFS 4
#define APU_IPC_SOFTIRQ_CLR_OFFS 8

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t start_apu;
	volatile uint32_t softirq_set;
	volatile uint32_t softirq_clr;
} apu_ipc_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                  START_APU                                   *
*******************************************************************************/

// Field: START_APU  Access: RW
// Reset: 0x0
// Set this flag to start APU execution. The APU always starts executing from
// the first address in APU RAM, so I recommend loading some code there first.
// Clearing this flag after the APU starts executing has no effect.
#define APU_IPC_START_APU_LSB  0
#define APU_IPC_START_APU_BITS 1
#define APU_IPC_START_APU_MASK 0x1

/*******************************************************************************
*                                 SOFTIRQ_SET                                  *
*******************************************************************************/

// Write bits to 1 to set soft IRQs. Read to check RISC-V soft IRQ status. Bit 1
// is the APU's flag, bit 0 is the CPU's flag.

// Field: SOFTIRQ_SET  Access: RWV
// Reset: 0x0
#define APU_IPC_SOFTIRQ_SET_LSB  0
#define APU_IPC_SOFTIRQ_SET_BITS 2
#define APU_IPC_SOFTIRQ_SET_MASK 0x3

/*******************************************************************************
*                                 SOFTIRQ_CLR                                  *
*******************************************************************************/

// Write bits to 1 to clear soft IRQs. Read to check RISC-V soft IRQ status. Bit
// 1 is the APU's flag, bit 0 is the CPU's flag.

// Field: SOFTIRQ_CLR  Access: RWV
// Reset: 0x0
#define APU_IPC_SOFTIRQ_CLR_LSB  0
#define APU_IPC_SOFTIRQ_CLR_BITS 2
#define APU_IPC_SOFTIRQ_CLR_MASK 0x3

#endif // _APU_IPC_REGS_H_
