/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _IPC_REGS_H_
#define _IPC_REGS_H_

// Block name           : ipc
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

#define IPC_SOFTIRQ_SET_OFFS 0
#define IPC_SOFTIRQ_CLR_OFFS 4

/*******************************************************************************
*                                 SOFTIRQ_SET                                  *
*******************************************************************************/

// Write bits to 1 to set soft IRQs. Read to check RISC-V soft IRQ status.

// Field: SOFTIRQ_SET  Access: RWV
// Reset: 0x0
#define IPC_SOFTIRQ_SET_LSB  0
#define IPC_SOFTIRQ_SET_BITS 2
#define IPC_SOFTIRQ_SET_MASK 0x3

/*******************************************************************************
*                                 SOFTIRQ_CLR                                  *
*******************************************************************************/

// Write bits to 1 to clear soft IRQs. Read to check RISC-V soft IRQ status.

// Field: SOFTIRQ_CLR  Access: RWV
// Reset: 0x0
#define IPC_SOFTIRQ_CLR_LSB  0
#define IPC_SOFTIRQ_CLR_BITS 2
#define IPC_SOFTIRQ_CLR_MASK 0x3

#endif // _IPC_REGS_H_
