/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : ipc
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

module ipc_regs (
	input wire         clk,
	input wire         rst_n,
	
	// AHB-Lite Port
	input  wire [15:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output wire [31:0] ahbls_hrdata,
	output wire        ahbls_hresp,
	
	// Register interfaces
	input  wire [1:0]  softirq_set_i,
	output reg  [1:0]  softirq_set_o,
	output reg         softirq_set_wen,
	input  wire [1:0]  softirq_clr_i,
	output reg  [1:0]  softirq_clr_o,
	output reg         softirq_clr_wen
);

// AHB-Lite adapter
wire [31:0] wdata = ahbls_hwdata;
reg         wen;
reg         ren;
reg  [15:0] addr;
always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 16'd0;
	end else if (ahbls_hready) begin
		wen <= ahbls_htrans[1] && ahbls_hwrite;
		ren <= ahbls_htrans[1] && !ahbls_hwrite;
		addr <= ahbls_haddr & 16'h4;
	end
end

reg  [31:0] rdata;
assign ahbls_hrdata = rdata;
assign ahbls_hready_resp = 1'b1;
assign ahbls_hresp = 1'b0;

localparam ADDR_SOFTIRQ_SET = 0;
localparam ADDR_SOFTIRQ_CLR = 4;

wire __softirq_set_wen = wen && addr == ADDR_SOFTIRQ_SET;
wire __softirq_set_ren = ren && addr == ADDR_SOFTIRQ_SET;
wire __softirq_clr_wen = wen && addr == ADDR_SOFTIRQ_CLR;
wire __softirq_clr_ren = ren && addr == ADDR_SOFTIRQ_CLR;

wire [1:0]  softirq_set_wdata = wdata[1:0];
wire [1:0]  softirq_set_rdata;
wire [31:0] __softirq_set_rdata = {30'h0, softirq_set_rdata};
assign softirq_set_rdata = softirq_set_i;

wire [1:0]  softirq_clr_wdata = wdata[1:0];
wire [1:0]  softirq_clr_rdata;
wire [31:0] __softirq_clr_rdata = {30'h0, softirq_clr_rdata};
assign softirq_clr_rdata = softirq_clr_i;

always @ (*) begin
	case (addr)
		ADDR_SOFTIRQ_SET: rdata = __softirq_set_rdata;
		ADDR_SOFTIRQ_CLR: rdata = __softirq_clr_rdata;
		default: rdata = 32'h0;
	endcase
	softirq_set_wen = __softirq_set_wen;
	softirq_set_o = softirq_set_wdata;
	softirq_clr_wen = __softirq_clr_wen;
	softirq_clr_o = softirq_clr_wdata;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
	end else begin
	end
end

endmodule
