/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : clocks
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 20

module clocks_regs (
	input wire         clk,
	input wire         rst_n,
	
	// APB Port
	input  wire        apbs_psel,
	input  wire        apbs_penable,
	input  wire        apbs_pwrite,
	input  wire [19:0] apbs_paddr,
	input  wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire        apbs_pready,
	output wire        apbs_pslverr,
	
	// Register interfaces
	output reg  [1:0]  clk_sys_select_o,
	input  wire [3:0]  clk_sys_selected_i,
	output reg  [1:0]  clk_audio_select_o,
	input  wire [3:0]  clk_audio_selected_i,
	output reg  [5:0]  mtime_tick_o
);

/* verilator lint_off UNUSEDSIGNAL */
// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg  [31:0] rdata;
reg         wen;
reg         ren;
reg  [19:0] addr;

assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_CLK_SYS = 0;
localparam ADDR_CLK_AUDIO = 4;
localparam ADDR_MTIME_TICK = 8;

wire __clk_sys_wen = wen && addr == ADDR_CLK_SYS;
wire __clk_sys_ren = ren && addr == ADDR_CLK_SYS;
wire __clk_audio_wen = wen && addr == ADDR_CLK_AUDIO;
wire __clk_audio_ren = ren && addr == ADDR_CLK_AUDIO;
wire __mtime_tick_wen = wen && addr == ADDR_MTIME_TICK;
wire __mtime_tick_ren = ren && addr == ADDR_MTIME_TICK;

wire [1:0]  clk_sys_select_wdata = wdata[1:0];
wire [1:0]  clk_sys_select_rdata;
wire [3:0]  clk_sys_selected_wdata = wdata[11:8];
wire [3:0]  clk_sys_selected_rdata;
wire [31:0] __clk_sys_rdata = {20'h0, clk_sys_selected_rdata, 6'h0, clk_sys_select_rdata};
assign clk_sys_select_rdata = clk_sys_select_o;
assign clk_sys_selected_rdata = clk_sys_selected_i;

wire [1:0]  clk_audio_select_wdata = wdata[1:0];
wire [1:0]  clk_audio_select_rdata;
wire [3:0]  clk_audio_selected_wdata = wdata[11:8];
wire [3:0]  clk_audio_selected_rdata;
wire [31:0] __clk_audio_rdata = {20'h0, clk_audio_selected_rdata, 6'h0, clk_audio_select_rdata};
assign clk_audio_select_rdata = clk_audio_select_o;
assign clk_audio_selected_rdata = clk_audio_selected_i;

wire [5:0]  mtime_tick_wdata = wdata[5:0];
wire [5:0]  mtime_tick_rdata;
wire [31:0] __mtime_tick_rdata = {26'h0, mtime_tick_rdata};
assign mtime_tick_rdata = mtime_tick_o;
/* verilator lint_on UNUSEDSIGNAL */

always @ (*) begin
	case (addr)
		ADDR_CLK_SYS: rdata = __clk_sys_rdata;
		ADDR_CLK_AUDIO: rdata = __clk_audio_rdata;
		ADDR_MTIME_TICK: rdata = __mtime_tick_rdata;
		default: rdata = 32'h0;
	endcase
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 20'd0;
		clk_sys_select_o <= 2'h2;
		clk_audio_select_o <= 2'h2;
		mtime_tick_o <= 6'h18;
	end else begin
		wen <= apbs_psel && !apbs_penable &&  apbs_pwrite;
		ren <= apbs_psel && !apbs_penable && !apbs_pwrite;
		if (apbs_psel && !apbs_penable) addr <= apbs_paddr & 20'hc;
		if (__clk_sys_wen)
			clk_sys_select_o <= clk_sys_select_wdata;
		if (__clk_audio_wen)
			clk_audio_select_o <= clk_audio_select_wdata;
		if (__mtime_tick_wen)
			mtime_tick_o <= mtime_tick_wdata;
	end
end

endmodule
