/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _CLOCKS_REGS_H_
#define _CLOCKS_REGS_H_

// Block name           : clocks
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 20

#define CLOCKS_CLK_SYS_OFFS 0
#define CLOCKS_CLK_AUDIO_OFFS 4
#define CLOCKS_MTIME_TICK_OFFS 8

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t clk_sys;
	volatile uint32_t clk_audio;
	volatile uint32_t mtime_tick;
} clocks_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                   CLK_SYS                                    *
*******************************************************************************/

// Controls for clk_sys

// Field: CLK_SYS_SELECT  Access: RW
// Reset: 0x2
// Select system clock source: 0-3 are CLK, CLK x 2/3, CLK x 1/2, DCK.
#define CLOCKS_CLK_SYS_SELECT_LSB  0
#define CLOCKS_CLK_SYS_SELECT_BITS 2
#define CLOCKS_CLK_SYS_SELECT_MASK 0x3
// Field: CLK_SYS_SELECTED  Access: ROV
// Reset: 0x0
// Currently selected clock mask status.
#define CLOCKS_CLK_SYS_SELECTED_LSB  8
#define CLOCKS_CLK_SYS_SELECTED_BITS 4
#define CLOCKS_CLK_SYS_SELECTED_MASK 0xf00

/*******************************************************************************
*                                  CLK_AUDIO                                   *
*******************************************************************************/

// Controls for clk_audio

// Field: CLK_AUDIO_SELECT  Access: RW
// Reset: 0x2
// Select audio clock source clock source: 0-3 are CLK, CLK x 2/3, CLK x 1/2,
// DCK.
#define CLOCKS_CLK_AUDIO_SELECT_LSB  0
#define CLOCKS_CLK_AUDIO_SELECT_BITS 2
#define CLOCKS_CLK_AUDIO_SELECT_MASK 0x3
// Field: CLK_AUDIO_SELECTED  Access: ROV
// Reset: 0x0
// Currently selected clock mask status.
#define CLOCKS_CLK_AUDIO_SELECTED_LSB  8
#define CLOCKS_CLK_AUDIO_SELECTED_BITS 4
#define CLOCKS_CLK_AUDIO_SELECTED_MASK 0xf00

/*******************************************************************************
*                                  MTIME_TICK                                  *
*******************************************************************************/

// Set number of clk_sys cycles per RISC-V timer tick.

// Field: MTIME_TICK  Access: RW
// Reset: 0x18
#define CLOCKS_MTIME_TICK_LSB  0
#define CLOCKS_MTIME_TICK_BITS 6
#define CLOCKS_MTIME_TICK_MASK 0x3f

#endif // _CLOCKS_REGS_H_
