/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : spi_stream
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

module spi_stream_regs (
	input wire         clk,
	input wire         rst_n,
	
	// AHB-Lite Port
	input  wire [15:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output wire [31:0] ahbls_hrdata,
	output wire        ahbls_hresp,
	
	// Register interfaces
	output reg         csr_start_o,
	input  wire        csr_busy_i,
	input  wire [1:0]  csr_flevel_i,
	output reg  [1:0]  csr_irqlevel_o,
	input  wire        csr_finished_i,
	output reg         csr_finished_o,
	output reg         csr_flush_o,
	output reg  [7:0]  csr_opcode_o,
	input  wire        csr_fvalid_i,
	output reg  [2:0]  clkdiv_o,
	input  wire [21:0] addr_i,
	output reg  [21:0] addr_o,
	output reg         addr_wen,
	input  wire [15:0] count_i,
	output reg  [15:0] count_o,
	output reg         count_wen,
	input  wire [31:0] fifo_i,
	output reg         fifo_ren,
	output reg         pause_req_o,
	input  wire        pause_ack_i
);

/* verilator lint_off UNUSEDSIGNAL */
// AHB-Lite adapter
wire [31:0] wdata = ahbls_hwdata;
reg         wen;
reg         ren;
reg  [15:0] addr;
always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 16'd0;
	end else if (ahbls_hready) begin
		wen <= ahbls_htrans[1] && ahbls_hwrite;
		ren <= ahbls_htrans[1] && !ahbls_hwrite;
		addr <= ahbls_haddr & 16'h1c;
	end
end

reg  [31:0] rdata;
assign ahbls_hrdata = rdata;
assign ahbls_hready_resp = 1'b1;
assign ahbls_hresp = 1'b0;

localparam ADDR_CSR = 0;
localparam ADDR_CLKDIV = 4;
localparam ADDR_ADDR = 8;
localparam ADDR_COUNT = 12;
localparam ADDR_FIFO = 16;
localparam ADDR_PAUSE = 20;

wire __csr_wen = wen && addr == ADDR_CSR;
wire __csr_ren = ren && addr == ADDR_CSR;
wire __clkdiv_wen = wen && addr == ADDR_CLKDIV;
wire __clkdiv_ren = ren && addr == ADDR_CLKDIV;
wire __addr_wen = wen && addr == ADDR_ADDR;
wire __addr_ren = ren && addr == ADDR_ADDR;
wire __count_wen = wen && addr == ADDR_COUNT;
wire __count_ren = ren && addr == ADDR_COUNT;
wire __fifo_wen = wen && addr == ADDR_FIFO;
wire __fifo_ren = ren && addr == ADDR_FIFO;
wire __pause_wen = wen && addr == ADDR_PAUSE;
wire __pause_ren = ren && addr == ADDR_PAUSE;

wire        csr_start_wdata = wdata[0];
wire        csr_start_rdata;
wire        csr_busy_wdata = wdata[1];
wire        csr_busy_rdata;
wire [1:0]  csr_flevel_wdata = wdata[5:4];
wire [1:0]  csr_flevel_rdata;
wire [1:0]  csr_irqlevel_wdata = wdata[9:8];
wire [1:0]  csr_irqlevel_rdata;
wire        csr_finished_wdata = wdata[14];
wire        csr_finished_rdata;
wire        csr_flush_wdata = wdata[15];
wire        csr_flush_rdata;
wire [7:0]  csr_opcode_wdata = wdata[23:16];
wire [7:0]  csr_opcode_rdata;
wire        csr_fvalid_wdata = wdata[31];
wire        csr_fvalid_rdata;
wire [31:0] __csr_rdata = {csr_fvalid_rdata, 7'h0, csr_opcode_rdata, csr_flush_rdata, csr_finished_rdata, 4'h0, csr_irqlevel_rdata, 2'h0, csr_flevel_rdata, 2'h0, csr_busy_rdata, csr_start_rdata};
assign csr_start_rdata = 1'h0;
assign csr_busy_rdata = csr_busy_i;
assign csr_flevel_rdata = csr_flevel_i;
assign csr_irqlevel_rdata = csr_irqlevel_o;
reg        csr_finished;
assign csr_finished_rdata = csr_finished;
assign csr_flush_rdata = 1'h0;
assign csr_opcode_rdata = csr_opcode_o;
assign csr_fvalid_rdata = csr_fvalid_i;

wire [2:0]  clkdiv_wdata = wdata[3:1];
wire [2:0]  clkdiv_rdata;
wire [31:0] __clkdiv_rdata = {28'h0, clkdiv_rdata, 1'h0};
assign clkdiv_rdata = clkdiv_o;

wire [21:0] addr_wdata = wdata[23:2];
wire [21:0] addr_rdata;
wire [31:0] __addr_rdata = {8'h0, addr_rdata, 2'h0};
assign addr_rdata = addr_i;

wire [15:0] count_wdata = wdata[15:0];
wire [15:0] count_rdata;
wire [31:0] __count_rdata = {16'h0, count_rdata};
assign count_rdata = count_i;

wire [31:0] fifo_wdata = wdata[31:0];
wire [31:0] fifo_rdata;
wire [31:0] __fifo_rdata = {fifo_rdata};
assign fifo_rdata = fifo_i;

wire        pause_req_wdata = wdata[0];
wire        pause_req_rdata;
wire        pause_ack_wdata = wdata[1];
wire        pause_ack_rdata;
wire [31:0] __pause_rdata = {30'h0, pause_ack_rdata, pause_req_rdata};
assign pause_req_rdata = pause_req_o;
assign pause_ack_rdata = pause_ack_i;
/* verilator lint_on UNUSEDSIGNAL */

always @ (*) begin
	case (addr)
		ADDR_CSR: rdata = __csr_rdata;
		ADDR_CLKDIV: rdata = __clkdiv_rdata;
		ADDR_ADDR: rdata = __addr_rdata;
		ADDR_COUNT: rdata = __count_rdata;
		ADDR_FIFO: rdata = __fifo_rdata;
		ADDR_PAUSE: rdata = __pause_rdata;
		default: rdata = 32'h0;
	endcase
	csr_start_o = csr_start_wdata & {1{__csr_wen}};
	csr_finished_o = csr_finished;
	csr_flush_o = csr_flush_wdata & {1{__csr_wen}};
	addr_wen = __addr_wen;
	addr_o = addr_wdata;
	count_wen = __count_wen;
	count_o = count_wdata;
	fifo_ren = __fifo_ren;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		csr_irqlevel_o <= 2'h0;
		csr_finished <= 1'h0;
		csr_opcode_o <= 8'hb;
		clkdiv_o <= 3'h1;
		pause_req_o <= 1'h0;
	end else begin
		if (__csr_wen)
			csr_irqlevel_o <= csr_irqlevel_wdata;
		csr_finished <= (csr_finished & ~({1{__csr_wen}} & csr_finished_wdata)) | csr_finished_i;
		if (__csr_wen)
			csr_opcode_o <= csr_opcode_wdata;
		if (__clkdiv_wen)
			clkdiv_o <= clkdiv_wdata;
		if (__pause_wen)
			pause_req_o <= pause_req_wdata;
	end
end

endmodule
