/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _SPI_STREAM_REGS_H_
#define _SPI_STREAM_REGS_H_

// Block name           : spi_stream
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

#define SPI_STREAM_CSR_OFFS 0
#define SPI_STREAM_CLKDIV_OFFS 4
#define SPI_STREAM_ADDR_OFFS 8
#define SPI_STREAM_COUNT_OFFS 12
#define SPI_STREAM_FIFO_OFFS 16
#define SPI_STREAM_PAUSE_OFFS 20

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t csr;
	volatile uint32_t clkdiv;
	volatile uint32_t addr;
	volatile uint32_t count;
	volatile uint32_t fifo;
	volatile uint32_t pause;
} spi_stream_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Control and status register

// Field: CSR_START  Access: SC
// Reset: 0x0
// Write 1 to start a sequence of COUNT transfers from the current value of
// ADDR. Do not use when BUSY is true.
#define SPI_STREAM_CSR_START_LSB  0
#define SPI_STREAM_CSR_START_BITS 1
#define SPI_STREAM_CSR_START_MASK 0x1
// Field: CSR_BUSY  Access: ROV
// Reset: 0x0
// More data is coming. Don't touch the configuration.
#define SPI_STREAM_CSR_BUSY_LSB  1
#define SPI_STREAM_CSR_BUSY_BITS 1
#define SPI_STREAM_CSR_BUSY_MASK 0x2
// Field: CSR_FLEVEL  Access: ROV
// Reset: 0x0
// Number of words currently stored in RX FIFO (0 to 2).
#define SPI_STREAM_CSR_FLEVEL_LSB  4
#define SPI_STREAM_CSR_FLEVEL_BITS 2
#define SPI_STREAM_CSR_FLEVEL_MASK 0x30
// Field: CSR_IRQLEVEL  Access: RW
// Reset: 0x0
// IRQ asserts when FLEVEL > IRQLEVEL.
#define SPI_STREAM_CSR_IRQLEVEL_LSB  8
#define SPI_STREAM_CSR_IRQLEVEL_BITS 2
#define SPI_STREAM_CSR_IRQLEVEL_MASK 0x300
// Field: CSR_FINISHED  Access: W1C
// Reset: 0x0
// Set when COUNT reaches 0 and the last data has been pushed to the FIFO. This
// also raises the IRQ. Write 1 to clear.
#define SPI_STREAM_CSR_FINISHED_LSB  14
#define SPI_STREAM_CSR_FINISHED_BITS 1
#define SPI_STREAM_CSR_FINISHED_MASK 0x4000
// Field: CSR_FLUSH  Access: SC
// Reset: 0x0
// Force the RX FIFO level to 0.
#define SPI_STREAM_CSR_FLUSH_LSB  15
#define SPI_STREAM_CSR_FLUSH_BITS 1
#define SPI_STREAM_CSR_FLUSH_MASK 0x8000
// Field: CSR_OPCODE  Access: RW
// Reset: 0xb
// Command to issue to SPI flash
#define SPI_STREAM_CSR_OPCODE_LSB  16
#define SPI_STREAM_CSR_OPCODE_BITS 8
#define SPI_STREAM_CSR_OPCODE_MASK 0xff0000
// Field: CSR_FVALID  Access: ROV
// Reset: 0x0
// True if the FIFO contains valid data (FLEVEL is not zero)
#define SPI_STREAM_CSR_FVALID_LSB  31
#define SPI_STREAM_CSR_FVALID_BITS 1
#define SPI_STREAM_CSR_FVALID_MASK 0x80000000

/*******************************************************************************
*                                    CLKDIV                                    *
*******************************************************************************/

// SPI SCK divisor. Only even values are supported (bit 0 is hardwired to 0).

// Field: CLKDIV  Access: RW
// Reset: 0x1
#define SPI_STREAM_CLKDIV_LSB  1
#define SPI_STREAM_CLKDIV_BITS 3
#define SPI_STREAM_CLKDIV_MASK 0xe

/*******************************************************************************
*                                     ADDR                                     *
*******************************************************************************/

// SPI address register (32-bit aligned)

// Field: ADDR  Access: RWV
// Reset: 0x0
#define SPI_STREAM_ADDR_LSB  2
#define SPI_STREAM_ADDR_BITS 22
#define SPI_STREAM_ADDR_MASK 0xfffffc

/*******************************************************************************
*                                    COUNT                                     *
*******************************************************************************/

// Number of words to read, starting from ADDR.

// Field: COUNT  Access: RWV
// Reset: 0x0
#define SPI_STREAM_COUNT_LSB  0
#define SPI_STREAM_COUNT_BITS 16
#define SPI_STREAM_COUNT_MASK 0xffff

/*******************************************************************************
*                                     FIFO                                     *
*******************************************************************************/

// Pop data from RX FIFO

// Field: FIFO  Access: RF
// Reset: 0x0
#define SPI_STREAM_FIFO_LSB  0
#define SPI_STREAM_FIFO_BITS 32
#define SPI_STREAM_FIFO_MASK 0xffffffff

/*******************************************************************************
*                                    PAUSE                                     *
*******************************************************************************/

// Pause the current stream and quiesce the SPI bus. This is intended to be used
// by the CPU to take control of the SPI GPIOs from the APU.

// Field: PAUSE_REQ  Access: RW
// Reset: 0x0
// Request pause of current stream.
#define SPI_STREAM_PAUSE_REQ_LSB  0
#define SPI_STREAM_PAUSE_REQ_BITS 1
#define SPI_STREAM_PAUSE_REQ_MASK 0x1
// Field: PAUSE_ACK  Access: ROV
// Reset: 0x0
// True if the bus is quiescent. The peripheral will not start any more
// transfers until PAUSE_REQ is released.
#define SPI_STREAM_PAUSE_ACK_LSB  1
#define SPI_STREAM_PAUSE_ACK_BITS 1
#define SPI_STREAM_PAUSE_ACK_MASK 0x2

#endif // _SPI_STREAM_REGS_H_
