/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _VUART_DEV_REGS_H_
#define _VUART_DEV_REGS_H_

// Block name           : vuart_dev
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define VUART_DEV_STAT_OFFS 0
#define VUART_DEV_INFO_OFFS 4
#define VUART_DEV_FIFO_OFFS 8
#define VUART_DEV_IRQCTRL_OFFS 12

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t stat;
	volatile uint32_t info;
	volatile uint32_t fifo;
	volatile uint32_t irqctrl;
} vuart_dev_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     STAT                                     *
*******************************************************************************/

// Field: STAT_RXVLD  Access: ROV
// Reset: 0x0
// Returns 1 when the device RX FIFO is valid (level is not zero)
#define VUART_DEV_STAT_RXVLD_LSB  31
#define VUART_DEV_STAT_RXVLD_BITS 1
#define VUART_DEV_STAT_RXVLD_MASK 0x80000000
// Field: STAT_TXRDY  Access: ROV
// Reset: 0x0
// Returns 1 when the device TX FIFO is ready (level is less than depth)
#define VUART_DEV_STAT_TXRDY_LSB  30
#define VUART_DEV_STAT_TXRDY_BITS 1
#define VUART_DEV_STAT_TXRDY_MASK 0x40000000
// Field: STAT_RXLEVEL  Access: ROV
// Reset: 0x0
// The current occupancy of the device RX FIFO
#define VUART_DEV_STAT_RXLEVEL_LSB  8
#define VUART_DEV_STAT_RXLEVEL_BITS 8
#define VUART_DEV_STAT_RXLEVEL_MASK 0xff00
// Field: STAT_TXLEVEL  Access: ROV
// Reset: 0x0
// The current occupancy of the device RX FIFO
#define VUART_DEV_STAT_TXLEVEL_LSB  0
#define VUART_DEV_STAT_TXLEVEL_BITS 8
#define VUART_DEV_STAT_TXLEVEL_MASK 0xff

/*******************************************************************************
*                                     INFO                                     *
*******************************************************************************/

// Field: INFO_RXSIZE  Access: ROV
// Reset: 0x0
// The maximum occupancy of the device RX FIFO, minus one.
#define VUART_DEV_INFO_RXSIZE_LSB  8
#define VUART_DEV_INFO_RXSIZE_BITS 8
#define VUART_DEV_INFO_RXSIZE_MASK 0xff00
// Field: INFO_TXSIZE  Access: ROV
// Reset: 0x0
// The maximum occupancy of the device TX FIFO, minus one.
#define VUART_DEV_INFO_TXSIZE_LSB  0
#define VUART_DEV_INFO_TXSIZE_BITS 8
#define VUART_DEV_INFO_TXSIZE_MASK 0xff

/*******************************************************************************
*                                     FIFO                                     *
*******************************************************************************/

// Field: FIFO_RXVLD  Access: ROV
// Reset: 0x0
// Returns 1 when the device RX FIFO is valid (level is not zero)
#define VUART_DEV_FIFO_RXVLD_LSB  31
#define VUART_DEV_FIFO_RXVLD_BITS 1
#define VUART_DEV_FIFO_RXVLD_MASK 0x80000000
// Field: FIFO_TXRDY  Access: ROV
// Reset: 0x0
// Returns 1 when the device TX FIFO is ready (level is less than depth)
#define VUART_DEV_FIFO_TXRDY_LSB  30
#define VUART_DEV_FIFO_TXRDY_BITS 1
#define VUART_DEV_FIFO_TXRDY_MASK 0x40000000
// Field: FIFO_TXRX  Access: RWF
// Reset: 0x0
// Bits written here are pushed to the device TX FIFO. Bits read from here are
// popped from the device RX FIFO.
#define VUART_DEV_FIFO_TXRX_LSB  0
#define VUART_DEV_FIFO_TXRX_BITS 8
#define VUART_DEV_FIFO_TXRX_MASK 0xff

/*******************************************************************************
*                                   IRQCTRL                                    *
*******************************************************************************/

// Field: IRQCTRL_RX_ENABLE  Access: RW
// Reset: 0x0
// Enable IRQ assertion when RX FIFO is not empty
#define VUART_DEV_IRQCTRL_RX_ENABLE_LSB  0
#define VUART_DEV_IRQCTRL_RX_ENABLE_BITS 1
#define VUART_DEV_IRQCTRL_RX_ENABLE_MASK 0x1
// Field: IRQCTRL_TX_ENABLE  Access: RW
// Reset: 0x0
// Enable IRQ assertion when TX FIFO is below the configured level
#define VUART_DEV_IRQCTRL_TX_ENABLE_LSB  1
#define VUART_DEV_IRQCTRL_TX_ENABLE_BITS 1
#define VUART_DEV_IRQCTRL_TX_ENABLE_MASK 0x2
// Field: IRQCTRL_TX_LEVEL  Access: RW
// Reset: 0x0
// 0: TX empty, 1, TX < 1/2, 2: TX < 3/4, 3: TX not full
#define VUART_DEV_IRQCTRL_TX_LEVEL_LSB  2
#define VUART_DEV_IRQCTRL_TX_LEVEL_BITS 2
#define VUART_DEV_IRQCTRL_TX_LEVEL_MASK 0xc

#endif // _VUART_DEV_REGS_H_
