/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : vuart_dev
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

module vuart_dev_regs (
	input wire         clk,
	input wire         rst_n,
	
	// APB Port
	input  wire        apbs_psel,
	input  wire        apbs_penable,
	input  wire        apbs_pwrite,
	input  wire [15:0] apbs_paddr,
	input  wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire        apbs_pready,
	output wire        apbs_pslverr,
	
	// Register interfaces
	input  wire        stat_rxvld_i,
	input  wire        stat_txrdy_i,
	input  wire        stat_hostconn_i,
	input  wire [7:0]  stat_rxlevel_i,
	input  wire [7:0]  stat_txlevel_i,
	input  wire [7:0]  info_rxsize_i,
	input  wire [7:0]  info_txsize_i,
	input  wire        fifo_rxvld_i,
	input  wire        fifo_txrdy_i,
	input  wire [7:0]  fifo_txrx_i,
	output reg  [7:0]  fifo_txrx_o,
	output reg         fifo_txrx_wen,
	output reg         fifo_txrx_ren,
	output reg         irqctrl_rx_enable_o,
	output reg         irqctrl_tx_enable_o,
	output reg  [1:0]  irqctrl_tx_level_o
);

// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg  [31:0] rdata;
reg         wen;
reg         ren;
reg  [15:0] addr;

assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_STAT = 0;
localparam ADDR_INFO = 4;
localparam ADDR_FIFO = 8;
localparam ADDR_IRQCTRL = 12;

wire __stat_wen = wen && addr == ADDR_STAT;
wire __stat_ren = ren && addr == ADDR_STAT;
wire __info_wen = wen && addr == ADDR_INFO;
wire __info_ren = ren && addr == ADDR_INFO;
wire __fifo_wen = wen && addr == ADDR_FIFO;
wire __fifo_ren = ren && addr == ADDR_FIFO;
wire __irqctrl_wen = wen && addr == ADDR_IRQCTRL;
wire __irqctrl_ren = ren && addr == ADDR_IRQCTRL;

wire        stat_rxvld_wdata = wdata[31];
wire        stat_rxvld_rdata;
wire        stat_txrdy_wdata = wdata[30];
wire        stat_txrdy_rdata;
wire        stat_hostconn_wdata = wdata[24];
wire        stat_hostconn_rdata;
wire [7:0]  stat_rxlevel_wdata = wdata[15:8];
wire [7:0]  stat_rxlevel_rdata;
wire [7:0]  stat_txlevel_wdata = wdata[7:0];
wire [7:0]  stat_txlevel_rdata;
wire [31:0] __stat_rdata = {stat_rxvld_rdata, stat_txrdy_rdata, 5'h0, stat_hostconn_rdata, 8'h0, stat_rxlevel_rdata, stat_txlevel_rdata};
assign stat_rxvld_rdata = stat_rxvld_i;
assign stat_txrdy_rdata = stat_txrdy_i;
assign stat_hostconn_rdata = stat_hostconn_i;
assign stat_rxlevel_rdata = stat_rxlevel_i;
assign stat_txlevel_rdata = stat_txlevel_i;

wire [7:0]  info_rxsize_wdata = wdata[15:8];
wire [7:0]  info_rxsize_rdata;
wire [7:0]  info_txsize_wdata = wdata[7:0];
wire [7:0]  info_txsize_rdata;
wire [31:0] __info_rdata = {16'h0, info_rxsize_rdata, info_txsize_rdata};
assign info_rxsize_rdata = info_rxsize_i;
assign info_txsize_rdata = info_txsize_i;

wire        fifo_rxvld_wdata = wdata[31];
wire        fifo_rxvld_rdata;
wire        fifo_txrdy_wdata = wdata[30];
wire        fifo_txrdy_rdata;
wire [7:0]  fifo_txrx_wdata = wdata[7:0];
wire [7:0]  fifo_txrx_rdata;
wire [31:0] __fifo_rdata = {fifo_rxvld_rdata, fifo_txrdy_rdata, 22'h0, fifo_txrx_rdata};
assign fifo_rxvld_rdata = fifo_rxvld_i;
assign fifo_txrdy_rdata = fifo_txrdy_i;
assign fifo_txrx_rdata = fifo_txrx_i;

wire        irqctrl_rx_enable_wdata = wdata[0];
wire        irqctrl_rx_enable_rdata;
wire        irqctrl_tx_enable_wdata = wdata[1];
wire        irqctrl_tx_enable_rdata;
wire [1:0]  irqctrl_tx_level_wdata = wdata[3:2];
wire [1:0]  irqctrl_tx_level_rdata;
wire [31:0] __irqctrl_rdata = {28'h0, irqctrl_tx_level_rdata, irqctrl_tx_enable_rdata, irqctrl_rx_enable_rdata};
assign irqctrl_rx_enable_rdata = irqctrl_rx_enable_o;
assign irqctrl_tx_enable_rdata = irqctrl_tx_enable_o;
assign irqctrl_tx_level_rdata = irqctrl_tx_level_o;

always @ (*) begin
	case (addr)
		ADDR_STAT: rdata = __stat_rdata;
		ADDR_INFO: rdata = __info_rdata;
		ADDR_FIFO: rdata = __fifo_rdata;
		ADDR_IRQCTRL: rdata = __irqctrl_rdata;
		default: rdata = 32'h0;
	endcase
	fifo_txrx_wen = __fifo_wen;
	fifo_txrx_o = fifo_txrx_wdata;
	fifo_txrx_ren = __fifo_ren;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 16'd0;
		irqctrl_rx_enable_o <= 1'h0;
		irqctrl_tx_enable_o <= 1'h0;
		irqctrl_tx_level_o <= 2'h0;
	end else begin
		wen <= apbs_psel && !apbs_penable &&  apbs_pwrite;
		ren <= apbs_psel && !apbs_penable && !apbs_pwrite;
		if (apbs_psel && !apbs_penable) addr <= apbs_paddr & 16'hc;
		if (__irqctrl_wen)
			irqctrl_rx_enable_o <= irqctrl_rx_enable_wdata;
		if (__irqctrl_wen)
			irqctrl_tx_enable_o <= irqctrl_tx_enable_wdata;
		if (__irqctrl_wen)
			irqctrl_tx_level_o <= irqctrl_tx_level_wdata;
	end
end

endmodule
