/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _VUART_HOST_REGS_H_
#define _VUART_HOST_REGS_H_

// Block name           : vuart_host
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 10

#define VUART_HOST_STAT_OFFS 0
#define VUART_HOST_INFO_OFFS 4
#define VUART_HOST_FIFO_OFFS 8

/*******************************************************************************
*                                     STAT                                     *
*******************************************************************************/

// Field: STAT_RXVLD  Access: ROV
// Reset: 0x0
// Returns 1 when the host RX FIFO is valid (level is not zero)
#define VUART_HOST_STAT_RXVLD_LSB  31
#define VUART_HOST_STAT_RXVLD_BITS 1
#define VUART_HOST_STAT_RXVLD_MASK 0x80000000
// Field: STAT_TXRDY  Access: ROV
// Reset: 0x0
// Returns 1 when the host TX FIFO is ready (level is less than depth)
#define VUART_HOST_STAT_TXRDY_LSB  30
#define VUART_HOST_STAT_TXRDY_BITS 1
#define VUART_HOST_STAT_TXRDY_MASK 0x40000000
// Field: STAT_RXLEVEL  Access: ROV
// Reset: 0x0
// The current occupancy of the host RX FIFO
#define VUART_HOST_STAT_RXLEVEL_LSB  8
#define VUART_HOST_STAT_RXLEVEL_BITS 8
#define VUART_HOST_STAT_RXLEVEL_MASK 0xff00
// Field: STAT_TXLEVEL  Access: ROV
// Reset: 0x0
// The current occupancy of the host RX FIFO
#define VUART_HOST_STAT_TXLEVEL_LSB  0
#define VUART_HOST_STAT_TXLEVEL_BITS 8
#define VUART_HOST_STAT_TXLEVEL_MASK 0xff

/*******************************************************************************
*                                     INFO                                     *
*******************************************************************************/

// Field: INFO_RXSIZE  Access: ROV
// Reset: 0x0
// The maximum occupancy of the host RX FIFO, minus one.
#define VUART_HOST_INFO_RXSIZE_LSB  8
#define VUART_HOST_INFO_RXSIZE_BITS 8
#define VUART_HOST_INFO_RXSIZE_MASK 0xff00
// Field: INFO_TXSIZE  Access: ROV
// Reset: 0x0
// The maximum occupancy of the host TX FIFO, minus one.
#define VUART_HOST_INFO_TXSIZE_LSB  0
#define VUART_HOST_INFO_TXSIZE_BITS 8
#define VUART_HOST_INFO_TXSIZE_MASK 0xff

/*******************************************************************************
*                                     FIFO                                     *
*******************************************************************************/

// Field: FIFO_RXVLD  Access: ROV
// Reset: 0x0
// Returns 1 when the host RX FIFO is valid (level is not zero)
#define VUART_HOST_FIFO_RXVLD_LSB  31
#define VUART_HOST_FIFO_RXVLD_BITS 1
#define VUART_HOST_FIFO_RXVLD_MASK 0x80000000
// Field: FIFO_TXRDY  Access: ROV
// Reset: 0x0
// Returns 1 when the host TX FIFO is ready (level is less than depth)
#define VUART_HOST_FIFO_TXRDY_LSB  30
#define VUART_HOST_FIFO_TXRDY_BITS 1
#define VUART_HOST_FIFO_TXRDY_MASK 0x40000000
// Field: FIFO_TXRX  Access: RWF
// Reset: 0x0
// Bits written here are pushed to the host TX FIFO. Bits read from here are
// popped from the host RX FIFO.
#define VUART_HOST_FIFO_TXRX_LSB  0
#define VUART_HOST_FIFO_TXRX_BITS 8
#define VUART_HOST_FIFO_TXRX_MASK 0xff

#endif // _VUART_HOST_REGS_H_
