/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : syscfg
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 20

// Register block for controls I had nowhere better to put

module syscfg_regs (
	input wire         clk,
	input wire         rst_n,
	
	// APB Port
	input  wire        apbs_psel,
	input  wire        apbs_penable,
	input  wire        apbs_pwrite,
	input  wire [19:0] apbs_paddr,
	input  wire [31:0] apbs_pwdata,
	output wire [31:0] apbs_prdata,
	output wire        apbs_pready,
	output wire        apbs_pslverr,
	
	// Register interfaces
	output reg  [5:0]  mtime_tick_o,
	output reg         sram_chicken_o
);

/* verilator lint_off UNUSEDSIGNAL */
// APB adapter
wire [31:0] wdata = apbs_pwdata;
reg  [31:0] rdata;
reg         wen;
reg         ren;
reg  [19:0] addr;

assign apbs_prdata = rdata;
assign apbs_pready = 1'b1;
assign apbs_pslverr = 1'b0;

localparam ADDR_MTIME_TICK = 0;
localparam ADDR_SRAM_CHICKEN = 4;

wire __mtime_tick_wen = wen && addr == ADDR_MTIME_TICK;
wire __mtime_tick_ren = ren && addr == ADDR_MTIME_TICK;
wire __sram_chicken_wen = wen && addr == ADDR_SRAM_CHICKEN;
wire __sram_chicken_ren = ren && addr == ADDR_SRAM_CHICKEN;

wire [5:0]  mtime_tick_wdata = wdata[5:0];
wire [5:0]  mtime_tick_rdata;
wire [31:0] __mtime_tick_rdata = {26'h0, mtime_tick_rdata};
assign mtime_tick_rdata = mtime_tick_o;

wire        sram_chicken_wdata = wdata[0];
wire        sram_chicken_rdata;
wire [31:0] __sram_chicken_rdata = {31'h0, sram_chicken_rdata};
assign sram_chicken_rdata = sram_chicken_o;
/* verilator lint_on UNUSEDSIGNAL */

always @ (*) begin
	case (addr)
		ADDR_MTIME_TICK: rdata = __mtime_tick_rdata;
		ADDR_SRAM_CHICKEN: rdata = __sram_chicken_rdata;
		default: rdata = 32'h0;
	endcase
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 20'd0;
		mtime_tick_o <= 6'h18;
		sram_chicken_o <= 1'h1;
	end else begin
		wen <= apbs_psel && !apbs_penable &&  apbs_pwrite;
		ren <= apbs_psel && !apbs_penable && !apbs_pwrite;
		if (apbs_psel && !apbs_penable) addr <= apbs_paddr & 20'h4;
		if (__mtime_tick_wen)
			mtime_tick_o <= mtime_tick_wdata;
		if (__sram_chicken_wen)
			sram_chicken_o <= sram_chicken_wdata;
	end
end

endmodule
