/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _SYSCFG_REGS_H_
#define _SYSCFG_REGS_H_

// Block name           : syscfg
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 20

// Register block for controls I had nowhere better to put

#define SYSCFG_MTIME_TICK_OFFS 0
#define SYSCFG_SRAM_CHICKEN_OFFS 4

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t mtime_tick;
	volatile uint32_t sram_chicken;
} syscfg_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                  MTIME_TICK                                  *
*******************************************************************************/

// The counter in MTIME increments once per MTIME_TICK cycles. This is intended
// to be a microsecond timebase, so set this register to the system clock
// frequency in MHz.

// Field: MTIME_TICK  Access: RW
// Reset: 0x18
#define SYSCFG_MTIME_TICK_LSB  0
#define SYSCFG_MTIME_TICK_BITS 6
#define SYSCFG_MTIME_TICK_MASK 0x3f

/*******************************************************************************
*                                 SRAM_CHICKEN                                 *
*******************************************************************************/

// The foundry SRAM models return incorrect data if chip select transitions on a
// clock edge. 99% sure this is just an issue with the model, but just in case,
// this register forces all SRAMs to be permanently enabled. You should clear
// this bit to avoid wasting power.

// Field: SRAM_CHICKEN  Access: RW
// Reset: 0x1
#define SYSCFG_SRAM_CHICKEN_LSB  0
#define SYSCFG_SRAM_CHICKEN_BITS 1
#define SYSCFG_SRAM_CHICKEN_MASK 0x1

#endif // _SYSCFG_REGS_H_
