/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _UART_REGS_H_
#define _UART_REGS_H_

// Block name           : uart
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define UART_CSR_OFFS 0
#define UART_DIV_OFFS 4
#define UART_FSTAT_OFFS 8
#define UART_TX_OFFS 12
#define UART_RX_OFFS 16
#define UART_IR_OFFS 20

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t csr;
	volatile uint32_t div;
	volatile uint32_t fstat;
	volatile uint32_t tx;
	volatile uint32_t rx;
	volatile uint32_t ir;
} uart_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Control and status register

// Field: CSR_EN  Access: RW
// Reset: 0x0
// UART runs when en is high. Synchronous reset (excluding FIFOs) when low.
#define UART_CSR_EN_LSB  0
#define UART_CSR_EN_BITS 1
#define UART_CSR_EN_MASK 0x1
// Field: CSR_BUSY  Access: ROV
// Reset: 0x0
// UART TX is still sending data
#define UART_CSR_BUSY_LSB  1
#define UART_CSR_BUSY_BITS 1
#define UART_CSR_BUSY_MASK 0x2
// Field: CSR_TXIE  Access: RW
// Reset: 0x0
// Enable TX FIFO interrupt
#define UART_CSR_TXIE_LSB  2
#define UART_CSR_TXIE_BITS 1
#define UART_CSR_TXIE_MASK 0x4
// Field: CSR_RXIE  Access: RW
// Reset: 0x0
// Enable RX FIFO interrupt
#define UART_CSR_RXIE_LSB  3
#define UART_CSR_RXIE_BITS 1
#define UART_CSR_RXIE_MASK 0x8
// Field: CSR_CTSEN  Access: RW
// Reset: 0x0
// Enable pausing of TX while CTS is not asserted
#define UART_CSR_CTSEN_LSB  4
#define UART_CSR_CTSEN_BITS 1
#define UART_CSR_CTSEN_MASK 0x10
// Field: CSR_LOOPBACK  Access: RW
// Reset: 0x0
// Connect TX -> RX and RTS -> CTS internally (for testing).
#define UART_CSR_LOOPBACK_LSB  8
#define UART_CSR_LOOPBACK_BITS 1
#define UART_CSR_LOOPBACK_MASK 0x100
// Field: CSR_TXFLUSH  Access: SC
// Reset: 0x0
// Force the TX FIFO level to 0.
#define UART_CSR_TXFLUSH_LSB  16
#define UART_CSR_TXFLUSH_BITS 1
#define UART_CSR_TXFLUSH_MASK 0x10000
// Field: CSR_RXFLUSH  Access: SC
// Reset: 0x0
// Force the RX FIFO level to 0.
#define UART_CSR_RXFLUSH_LSB  17
#define UART_CSR_RXFLUSH_BITS 1
#define UART_CSR_RXFLUSH_MASK 0x20000

/*******************************************************************************
*                                     DIV                                      *
*******************************************************************************/

// Clock divider control fields

// Field: DIV_INT  Access: WO
// Reset: 0x1
#define UART_DIV_INT_LSB  4
#define UART_DIV_INT_BITS 12
#define UART_DIV_INT_MASK 0xfff0
// Field: DIV_FRAC  Access: WO
// Reset: 0x0
#define UART_DIV_FRAC_LSB  0
#define UART_DIV_FRAC_BITS 4
#define UART_DIV_FRAC_MASK 0xf

/*******************************************************************************
*                                    FSTAT                                     *
*******************************************************************************/

// FIFO status register

// Field: FSTAT_TXLEVEL  Access: ROV
// Reset: 0x0
#define UART_FSTAT_TXLEVEL_LSB  0
#define UART_FSTAT_TXLEVEL_BITS 8
#define UART_FSTAT_TXLEVEL_MASK 0xff
// Field: FSTAT_TXFULL  Access: ROV
// Reset: 0x0
#define UART_FSTAT_TXFULL_LSB  8
#define UART_FSTAT_TXFULL_BITS 1
#define UART_FSTAT_TXFULL_MASK 0x100
// Field: FSTAT_TXEMPTY  Access: ROV
// Reset: 0x0
#define UART_FSTAT_TXEMPTY_LSB  9
#define UART_FSTAT_TXEMPTY_BITS 1
#define UART_FSTAT_TXEMPTY_MASK 0x200
// Field: FSTAT_TXOVER  Access: W1C
// Reset: 0x0
#define UART_FSTAT_TXOVER_LSB  10
#define UART_FSTAT_TXOVER_BITS 1
#define UART_FSTAT_TXOVER_MASK 0x400
// Field: FSTAT_TXUNDER  Access: W1C
// Reset: 0x0
#define UART_FSTAT_TXUNDER_LSB  11
#define UART_FSTAT_TXUNDER_BITS 1
#define UART_FSTAT_TXUNDER_MASK 0x800
// Field: FSTAT_RXLEVEL  Access: ROV
// Reset: 0x0
#define UART_FSTAT_RXLEVEL_LSB  16
#define UART_FSTAT_RXLEVEL_BITS 8
#define UART_FSTAT_RXLEVEL_MASK 0xff0000
// Field: FSTAT_RXFULL  Access: ROV
// Reset: 0x0
#define UART_FSTAT_RXFULL_LSB  24
#define UART_FSTAT_RXFULL_BITS 1
#define UART_FSTAT_RXFULL_MASK 0x1000000
// Field: FSTAT_RXEMPTY  Access: ROV
// Reset: 0x0
#define UART_FSTAT_RXEMPTY_LSB  25
#define UART_FSTAT_RXEMPTY_BITS 1
#define UART_FSTAT_RXEMPTY_MASK 0x2000000
// Field: FSTAT_RXOVER  Access: W1C
// Reset: 0x0
#define UART_FSTAT_RXOVER_LSB  26
#define UART_FSTAT_RXOVER_BITS 1
#define UART_FSTAT_RXOVER_MASK 0x4000000
// Field: FSTAT_RXUNDER  Access: W1C
// Reset: 0x0
#define UART_FSTAT_RXUNDER_LSB  27
#define UART_FSTAT_RXUNDER_BITS 1
#define UART_FSTAT_RXUNDER_MASK 0x8000000

/*******************************************************************************
*                                      TX                                      *
*******************************************************************************/

// TX data FIFO

// Field: TX  Access: WF
// Reset: 0x0
#define UART_TX_LSB  0
#define UART_TX_BITS 8
#define UART_TX_MASK 0xff

/*******************************************************************************
*                                      RX                                      *
*******************************************************************************/

// RX data FIFO

// Field: RX  Access: RF
// Reset: 0x0
#define UART_RX_LSB  0
#define UART_RX_BITS 8
#define UART_RX_MASK 0xff

/*******************************************************************************
*                                      IR                                      *
*******************************************************************************/

// Control for infrared transmit mode

// Field: IR_DIV  Access: RW
// Reset: 0x0
// Configure IR modulation frequency. Modulation period is 2 x (DIV + 1) cycles.
// For example, 38 kHz from a 24 MHz clock would be DIV=315 (0.1% error).
#define UART_IR_DIV_LSB  0
#define UART_IR_DIV_BITS 12
#define UART_IR_DIV_MASK 0xfff
// Field: IR_EN  Access: RW
// Reset: 0x0
// Enable modulation. The modulation is an OR gate, with an optional invert on
// the TX line before and after.
#define UART_IR_EN_LSB  20
#define UART_IR_EN_BITS 1
#define UART_IR_EN_MASK 0x100000
// Field: IR_PREINVERT_TX  Access: RW
// Reset: 0x0
// Invert before the modulation OR gate.
#define UART_IR_PREINVERT_TX_LSB  21
#define UART_IR_PREINVERT_TX_BITS 1
#define UART_IR_PREINVERT_TX_MASK 0x200000
// Field: IR_POSTINVERT_TX  Access: RW
// Reset: 0x0
// Invert after the modulation OR gate.
#define UART_IR_POSTINVERT_TX_LSB  22
#define UART_IR_POSTINVERT_TX_BITS 1
#define UART_IR_POSTINVERT_TX_MASK 0x400000
// Field: IR_INVERT_RX  Access: RW
// Reset: 0x0
// Invert the RX input.
#define UART_IR_INVERT_RX_LSB  23
#define UART_IR_INVERT_RX_BITS 1
#define UART_IR_INVERT_RX_MASK 0x800000

#endif // _UART_REGS_H_
