/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _DISPCTRL_RB180_REGS_H_
#define _DISPCTRL_RB180_REGS_H_

// Block name           : dispctrl_rb180
// Bus type             : apb
// Bus data width       : 32
// Bus address width    : 16

#define DISPCTRL_RB180_CSR_OFFS 0
#define DISPCTRL_RB180_SCANBUF_SIZE_OFFS 4
#define DISPCTRL_RB180_PXFIFO_OFFS 8
#define DISPCTRL_RB180_BL_PWM_OFFS 12

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t csr;
	volatile uint32_t scanbuf_size;
	volatile uint32_t pxfifo;
	volatile uint32_t bl_pwm;
} dispctrl_rb180_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Control and status register for the SPI LCD interface

// Field: CSR_SCAN_EN  Access: RW
// Reset: 0x0
// Enable reading of scanbuffers presented by the PPU into the pixel FIFO.
#define DISPCTRL_RB180_CSR_SCAN_EN_LSB  0
#define DISPCTRL_RB180_CSR_SCAN_EN_BITS 1
#define DISPCTRL_RB180_CSR_SCAN_EN_MASK 0x1
// Field: CSR_PXFIFO_EMPTY  Access: ROV
// Reset: 0x0
#define DISPCTRL_RB180_CSR_PXFIFO_EMPTY_LSB  2
#define DISPCTRL_RB180_CSR_PXFIFO_EMPTY_BITS 1
#define DISPCTRL_RB180_CSR_PXFIFO_EMPTY_MASK 0x4
// Field: CSR_PXFIFO_FULL  Access: ROV
// Reset: 0x0
#define DISPCTRL_RB180_CSR_PXFIFO_FULL_LSB  3
#define DISPCTRL_RB180_CSR_PXFIFO_FULL_BITS 1
#define DISPCTRL_RB180_CSR_PXFIFO_FULL_MASK 0x8
// Field: CSR_LCD_CS  Access: RW
// Reset: 0x1
#define DISPCTRL_RB180_CSR_LCD_CS_LSB  8
#define DISPCTRL_RB180_CSR_LCD_CS_BITS 1
#define DISPCTRL_RB180_CSR_LCD_CS_MASK 0x100
// Field: CSR_LCD_DC  Access: RW
// Reset: 0x0
#define DISPCTRL_RB180_CSR_LCD_DC_LSB  9
#define DISPCTRL_RB180_CSR_LCD_DC_BITS 1
#define DISPCTRL_RB180_CSR_LCD_DC_MASK 0x200
// Field: CSR_TX_BUSY  Access: ROV
// Reset: 0x0
#define DISPCTRL_RB180_CSR_TX_BUSY_LSB  10
#define DISPCTRL_RB180_CSR_TX_BUSY_BITS 1
#define DISPCTRL_RB180_CSR_TX_BUSY_MASK 0x400
// Field: CSR_LCD_SHIFTCNT  Access: RW
// Reset: 0x0
// If 1, shift out 16 bits from each pixel FIFO entry. If 0, shift out 8 bits
// (e.g. commands).
#define DISPCTRL_RB180_CSR_LCD_SHIFTCNT_LSB  16
#define DISPCTRL_RB180_CSR_LCD_SHIFTCNT_BITS 1
#define DISPCTRL_RB180_CSR_LCD_SHIFTCNT_MASK 0x10000
// Field: CSR_LCD_BUSWIDTH  Access: RW
// Reset: 0x0
// 1 for 8-bit, 0 for serial. LCD_DAT[1] is used as CSn in serial mode.
#define DISPCTRL_RB180_CSR_LCD_BUSWIDTH_LSB  17
#define DISPCTRL_RB180_CSR_LCD_BUSWIDTH_BITS 1
#define DISPCTRL_RB180_CSR_LCD_BUSWIDTH_MASK 0x20000
// Field: CSR_LCD_HALFRATE  Access: RW
// Reset: 0x0
// If 1, only write to the LCD every other cycle (to meet minimum write cycle
// times).
#define DISPCTRL_RB180_CSR_LCD_HALFRATE_LSB  18
#define DISPCTRL_RB180_CSR_LCD_HALFRATE_BITS 1
#define DISPCTRL_RB180_CSR_LCD_HALFRATE_MASK 0x40000
// Field: CSR_XDOUBLE  Access: RW
// Reset: 0x0
// Send each pixel read from the scanbuffer to the LCD twice. The number of
// pixels read from the scan buffer does not change. This effectively halves the
// horizontal resolution of the display.
#define DISPCTRL_RB180_CSR_XDOUBLE_LSB  20
#define DISPCTRL_RB180_CSR_XDOUBLE_BITS 1
#define DISPCTRL_RB180_CSR_XDOUBLE_MASK 0x100000
// Field: CSR_YDOUBLE  Access: RW
// Reset: 0x0
// Read each scan buffer twice before releasing it back to the PPU.
#define DISPCTRL_RB180_CSR_YDOUBLE_LSB  21
#define DISPCTRL_RB180_CSR_YDOUBLE_BITS 1
#define DISPCTRL_RB180_CSR_YDOUBLE_MASK 0x200000
// Field: CSR_DISPTYPE  Access: RO
// Reset: 0x2
// Encodes the type of display controller. All RISCBoy display controllers have
// this field. 0x2 means RISCBoy 180 controller.
#define DISPCTRL_RB180_CSR_DISPTYPE_LSB  28
#define DISPCTRL_RB180_CSR_DISPTYPE_BITS 4
#define DISPCTRL_RB180_CSR_DISPTYPE_MASK 0xf0000000

/*******************************************************************************
*                                 SCANBUF_SIZE                                 *
*******************************************************************************/

// Set the number of pixels to be read from one scan buffer before releasing it
// back to the PPU. On RB180 the scan buffers are 512 pixels in size.

// Field: SCANBUF_SIZE  Access: RW
// Reset: 0x13f
#define DISPCTRL_RB180_SCANBUF_SIZE_LSB  0
#define DISPCTRL_RB180_SCANBUF_SIZE_BITS 9
#define DISPCTRL_RB180_SCANBUF_SIZE_MASK 0x1ff

/*******************************************************************************
*                                    PXFIFO                                    *
*******************************************************************************/

// Direct write access to the pixel FIFO. Must only be used when the PPU is
// idle.

// Field: PXFIFO  Access: WF
// Reset: 0x0
#define DISPCTRL_RB180_PXFIFO_LSB  0
#define DISPCTRL_RB180_PXFIFO_BITS 16
#define DISPCTRL_RB180_PXFIFO_MASK 0xffff

/*******************************************************************************
*                                    BL_PWM                                    *
*******************************************************************************/

// Control backlight PWM pin

// Field: BL_PWM_DIV  Access: RW
// Reset: 0x5e
// PWM period is 255 x DIV. Value of 0 is interpreted as divisor of 256.
#define DISPCTRL_RB180_BL_PWM_DIV_LSB  16
#define DISPCTRL_RB180_BL_PWM_DIV_BITS 8
#define DISPCTRL_RB180_BL_PWM_DIV_MASK 0xff0000
// Field: BL_PWM_LEVEL  Access: RW
// Reset: 0x0
// Value of 0 means 0%. Value of 255 means 100%. Varies linearly in between.
#define DISPCTRL_RB180_BL_PWM_LEVEL_LSB  0
#define DISPCTRL_RB180_BL_PWM_LEVEL_BITS 8
#define DISPCTRL_RB180_BL_PWM_LEVEL_MASK 0xff

#endif // _DISPCTRL_RB180_REGS_H_
