#!/usr/bin/env python3

import argparse
import struct
import sys
import zlib

PADDED_SIZE = 1024

parser = argparse.ArgumentParser()
parser.add_argument("src", help="Source binary file (max 4092 bytes)")
parser.add_argument("dst", help="Destination binary file")
args = parser.parse_args()

data_bytes = open(args.src, "rb").read()

if len(data_bytes) > PADDED_SIZE - 4:
	sys.exit(f"File size of {len(data_bytes)} bytes exceeds limit of {PADDED_SIZE - 4}")

data_bytes = data_bytes + bytes(PADDED_SIZE - 4 - len(data_bytes))
data_bytes = data_bytes + struct.pack("<L", zlib.adler32(data_bytes))

open(args.dst, "wb").write(data_bytes)