#!/bin/bash

headers=$(find ../../../hdl -name "*.h" | xargs grep -l "AUTOGENERATED BY REGBLOCK" | grep -v "riscboy/software")

# Start by linking everything we find
rm *.h
for header in ${headers}; do
	ln -sf ${header} $(basename ${header})
done

# Remove irrelevant headers
rm ppu_dispctrl_dvi_regs.h
rm sdram_ctrl_regs.h
rm spi_03h_xip_regs.h
rm spi_regs.h
rm uart_regs.h

# Force correct header when ambiguous
rm gpio_regs.h
ln -sf ../../../hdl/gpio/gpio_regs.h gpio_regs.h