// Generated by bin2rom, do not modify directly.
// Source: /home/luke/proj/riscboy-180/software/bootrom/build/bootrom.bin

`default_nettype none

module ahb_rom_boot (
	input  wire        clk,
	input  wire        rst_n,
	
	// AHB-Lite Port
	input  wire [19:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output wire [31:0] ahbls_hrdata,
	output wire        ahbls_hresp
);

localparam [19:0] ADDR_MASK = 20'hfc;

reg [19:0] addr_q;
wire [19:0] addr = addr_q & ADDR_MASK;

always @ (posedge clk) if (ahbls_htrans[1] && ahbls_hready) begin
	addr_q <= ahbls_haddr & ADDR_MASK;
end

reg [31:0] rom_rdata;
always @ (*) case (addr)
	20'h0: rom_rdata = 32'h44fd447d;
	20'h4: rom_rdata = 32'hfcfd14fd;
	20'h8: rom_rdata = 32'hfc65147d;
	20'hc: rom_rdata = 32'h00082137;
	20'h10: rom_rdata = 32'hc0010593;
	20'h14: rom_rdata = 32'hc1884501;
	20'h18: rom_rdata = 32'heee30591;
	20'h1c: rom_rdata = 32'h6437fe25;
	20'h20: rom_rdata = 32'h2023000e;
	20'h24: rom_rdata = 32'h479d0004;
	20'h28: rom_rdata = 32'h00080bb7;
	20'h2c: rom_rdata = 32'h4501c81c;
	20'h30: rom_rdata = 32'h69414c11;
	20'h34: rom_rdata = 32'h28ad79c1;
	20'h38: rom_rdata = 32'h24234481;
	20'h3c: rom_rdata = 32'h8a930184;
	20'h40: rom_rdata = 32'h1941400b;
	20'h44: rom_rdata = 32'h8b1309bd;
	20'h48: rom_rdata = 32'hf5133fcb;
	20'h4c: rom_rdata = 32'h05320014;
	20'h50: rom_rdata = 32'h29851513;
	20'h54: rom_rdata = 32'h01842623;
	20'h58: rom_rdata = 32'h29951513;
	20'h5c: rom_rdata = 32'h0a372891;
	20'h60: rom_rdata = 32'h45010008;
	20'h64: rom_rdata = 32'h202320b1;
	20'h68: rom_rdata = 32'h0a1100aa;
	20'h6c: rom_rdata = 32'hff5a1be3;
	20'h70: rom_rdata = 32'h01842423;
	20'h74: rom_rdata = 32'h3fcba603;
	20'h78: rom_rdata = 32'h000806b7;
	20'h7c: rom_rdata = 32'h47054781;
	20'h80: rom_rdata = 32'h972e828c;
	20'h84: rom_rdata = 32'h00e97363;
	20'h88: rom_rdata = 32'h97ba974e;
	20'h8c: rom_rdata = 32'h00f97363;
	20'h90: rom_rdata = 32'h068597ce;
	20'h94: rom_rdata = 32'hff6696e3;
	20'h98: rom_rdata = 32'h08f747b3;
	20'h9c: rom_rdata = 32'h00f61363;
	20'ha0: rom_rdata = 32'h04859b82;
	20'ha4: rom_rdata = 32'h92e347a9;
	20'ha8: rom_rdata = 32'h0073faf4;
	20'hac: rom_rdata = 32'hbff51050;
	20'hb0: rom_rdata = 32'h02000693;
	20'hb4: rom_rdata = 32'h67374781;
	20'hb8: rom_rdata = 32'h4805000e;
	20'hbc: rom_rdata = 32'h51634589;
	20'hc0: rom_rdata = 32'h24230205;
	20'hc4: rom_rdata = 32'hc34c0107;
	20'hc8: rom_rdata = 32'h07865310;
	20'hcc: rom_rdata = 32'h5613c34c;
	20'hd0: rom_rdata = 32'h16fd4836;
	20'hd4: rom_rdata = 32'h8fd10506;
	20'hd8: rom_rdata = 32'hd513f2fd;
	20'hdc: rom_rdata = 32'h80826987;
	20'he0: rom_rdata = 32'h01072623;
	20'he4: rom_rdata = 32'h0000b7cd;
	default: rom_rdata = 32'hxxxxxxxx;
endcase

reg ready;
always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		ready <= 1'b1;
	end else if (ahbls_hready && ahbls_htrans[1]) begin
		ready <= 1'b0;
	end else begin
		ready <= 1'b1;
	end
end

reg [31:0] q;
always @ (posedge clk) begin
	q <= rom_rdata;
end

assign ahbls_hresp = 1'b0;
assign ahbls_hready_resp = ready;
assign ahbls_hrdata = q;

endmodule

`ifndef YOSYS
`default_nettype wire
`endif
