// Generated by bin2rom, do not modify directly.
// Source: /Users/luke/proj/riscboy-180/software/bootrom/build/bootrom.bin

`default_nettype none

module ahb_rom_boot (
	input  wire        clk,
	input  wire        rst_n,
	
	// AHB-Lite Port
	input  wire [19:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output reg  [31:0] ahbls_hrdata,
	output wire        ahbls_hresp
);

localparam [19:0] ADDR_MASK = 20'hfc;

reg [19:0] addr;

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		addr <= {20{1'b0}};
	end else if (ahbls_hready) begin
		addr <= ahbls_haddr & ADDR_MASK;
	end
end

assign ahbls_hready_resp = 1'b1;
assign ahbls_hresp = 1'b0;

always @ (*) case (addr)
	20'h0: ahbls_hrdata = 32'h44fd447d;
	20'h4: ahbls_hrdata = 32'hfcfd14fd;
	20'h8: ahbls_hrdata = 32'hfc65147d;
	20'hc: ahbls_hrdata = 32'h00082137;
	20'h10: ahbls_hrdata = 32'hc0010593;
	20'h14: ahbls_hrdata = 32'hc1884501;
	20'h18: ahbls_hrdata = 32'heee30591;
	20'h1c: ahbls_hrdata = 32'h1101fe25;
	20'h20: ahbls_hrdata = 32'hca26cc22;
	20'h24: ahbls_hrdata = 32'hce06c84a;
	20'h28: ahbls_hrdata = 32'h4401c64e;
	20'h2c: ahbls_hrdata = 32'h00081937;
	20'h30: ahbls_hrdata = 32'h771344a9;
	20'h34: ahbls_hrdata = 32'h07320014;
	20'h38: ahbls_hrdata = 32'h000807b7;
	20'h3c: ahbls_hrdata = 32'h8b944681;
	20'h40: ahbls_hrdata = 32'h07050785;
	20'h44: ahbls_hrdata = 32'hff279ce3;
	20'h48: ahbls_hrdata = 32'hffc7a983;
	20'h4c: ahbls_hrdata = 32'h15f16585;
	20'h50: ahbls_hrdata = 32'h00080537;
	20'h54: ahbls_hrdata = 32'h95632821;
	20'h58: ahbls_hrdata = 32'h07b700a9;
	20'h5c: ahbls_hrdata = 32'h97820008;
	20'h60: ahbls_hrdata = 32'h18e30405;
	20'h64: ahbls_hrdata = 32'h0073fc94;
	20'h68: ahbls_hrdata = 32'hbff51050;
	20'h6c: ahbls_hrdata = 32'h78416641;
	20'h70: ahbls_hrdata = 32'h47014681;
	20'h74: ahbls_hrdata = 32'h16414785;
	20'h78: ahbls_hrdata = 32'h9563083d;
	20'h7c: ahbls_hrdata = 32'hc53300b6;
	20'h80: ahbls_hrdata = 32'h808208e7;
	20'h84: ahbls_hrdata = 32'h00d508b3;
	20'h88: ahbls_hrdata = 32'h0008c883;
	20'h8c: ahbls_hrdata = 32'h736397c6;
	20'h90: ahbls_hrdata = 32'h97c200f6;
	20'h94: ahbls_hrdata = 32'h7363973e;
	20'h98: ahbls_hrdata = 32'h974200e6;
	20'h9c: ahbls_hrdata = 32'hbff10685;
	default: ahbls_hrdata = 32'h00000000;
endcase

endmodule

`ifndef YOSYS
`default_nettype wire
`endif
