// Generated by bin2rom, do not modify directly.
// Source: /home/luke/proj/riscboy-180/software/bootrom/build/bootrom.bin

`default_nettype none

module ahb_rom_boot (
	input  wire        clk,
	input  wire        rst_n,
	
	// AHB-Lite Port
	input  wire [19:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output wire [31:0] ahbls_hrdata,
	output wire        ahbls_hresp
);

localparam [19:0] ADDR_MASK = 20'hfc;

reg [19:0] addr_q;
wire [19:0] addr = addr_q & ADDR_MASK;

always @ (posedge clk) if (ahbls_htrans[1] && ahbls_hready) begin
	addr_q <= ahbls_haddr & ADDR_MASK;
end

reg [31:0] rom_rdata;
always @ (*) case (addr)
	20'h0: rom_rdata = 32'h44fd447d;
	20'h4: rom_rdata = 32'hfcfd14fd;
	20'h8: rom_rdata = 32'hfc65147d;
	20'hc: rom_rdata = 32'h000e67b7;
	20'h10: rom_rdata = 32'hd798473d;
	20'h14: rom_rdata = 32'h00080e37;
	20'h18: rom_rdata = 32'h000cb737;
	20'h1c: rom_rdata = 32'h65c147a1;
	20'h20: rom_rdata = 32'hc35c7541;
	20'h24: rom_rdata = 32'h0f134601;
	20'h28: rom_rdata = 32'h08930ff0;
	20'h2c: rom_rdata = 32'h15c1400e;
	20'h30: rom_rdata = 32'h0313053d;
	20'h34: rom_rdata = 32'h4ea93fce;
	20'h38: rom_rdata = 32'h00167793;
	20'h3c: rom_rdata = 32'hc71c07b2;
	20'h40: rom_rdata = 32'h01e72623;
	20'h44: rom_rdata = 32'he793431c;
	20'h48: rom_rdata = 32'hc31c0017;
	20'h4c: rom_rdata = 32'h000807b7;
	20'h50: rom_rdata = 32'hdfe34314;
	20'h54: rom_rdata = 32'h4b14fe06;
	20'h58: rom_rdata = 32'h0791c394;
	20'h5c: rom_rdata = 32'hff179ae3;
	20'h60: rom_rdata = 32'h3fce2f83;
	20'h64: rom_rdata = 32'h00080837;
	20'h68: rom_rdata = 32'h46854781;
	20'h6c: rom_rdata = 32'h00084283;
	20'h70: rom_rdata = 32'hf3639696;
	20'h74: rom_rdata = 32'h96aa00d5;
	20'h78: rom_rdata = 32'hf36397b6;
	20'h7c: rom_rdata = 32'h97aa00f5;
	20'h80: rom_rdata = 32'h15e30805;
	20'h84: rom_rdata = 32'hc7b3fe68;
	20'h88: rom_rdata = 32'h936308f6;
	20'h8c: rom_rdata = 32'h9e0200ff;
	20'h90: rom_rdata = 32'h13e30605;
	20'h94: rom_rdata = 32'h0073fbd6;
	20'h98: rom_rdata = 32'hbff51050;
	default: rom_rdata = 32'hxxxxxxxx;
endcase

reg ready;
always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		ready <= 1'b1;
	end else if (ahbls_hready && ahbls_htrans[1]) begin
		ready <= 1'b0;
	end else begin
		ready <= 1'b1;
	end
end

reg [31:0] q;
always @ (posedge clk) begin
	q <= rom_rdata;
end

assign ahbls_hresp = 1'b0;
assign ahbls_hready_resp = ready;
assign ahbls_hrdata = q;

endmodule

`ifndef YOSYS
`default_nettype wire
`endif
