/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _APU_TIMER_REGS_H_
#define _APU_TIMER_REGS_H_

// Block name           : apu_timer
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

#define APU_TIMER_CSR_OFFS 0
#define APU_TIMER_TICK_OFFS 4
#define APU_TIMER_RELOAD0_OFFS 8
#define APU_TIMER_CTR0_OFFS 12
#define APU_TIMER_RELOAD1_OFFS 16
#define APU_TIMER_CTR1_OFFS 20
#define APU_TIMER_RELOAD2_OFFS 24
#define APU_TIMER_CTR2_OFFS 28

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t csr;
	volatile uint32_t tick;
	volatile uint32_t reload0;
	volatile uint32_t ctr0;
	volatile uint32_t reload1;
	volatile uint32_t ctr1;
	volatile uint32_t reload2;
	volatile uint32_t ctr2;
} apu_timer_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Field: CSR_EN  Access: RW
// Reset: 0x0
#define APU_TIMER_CSR_EN_LSB  0
#define APU_TIMER_CSR_EN_BITS 3
#define APU_TIMER_CSR_EN_MASK 0x7
// Field: CSR_RELOAD  Access: RW
// Reset: 0x0
#define APU_TIMER_CSR_RELOAD_LSB  8
#define APU_TIMER_CSR_RELOAD_BITS 3
#define APU_TIMER_CSR_RELOAD_MASK 0x700
// Field: CSR_IRQ  Access: W1C
// Reset: 0x0
// Interrupt status -- write one to clear each bit
#define APU_TIMER_CSR_IRQ_LSB  16
#define APU_TIMER_CSR_IRQ_BITS 3
#define APU_TIMER_CSR_IRQ_MASK 0x70000

/*******************************************************************************
*                                     TICK                                     *
*******************************************************************************/

// Field: TICK  Access: RW
// Reset: 0x17
// All counters decrement once every TICK + 1 cycles.
#define APU_TIMER_TICK_LSB  0
#define APU_TIMER_TICK_BITS 8
#define APU_TIMER_TICK_MASK 0xff

/*******************************************************************************
*                                   RELOAD0                                    *
*******************************************************************************/

// Reload value for counter 0. The counter takes this value on the next tick
// after reaching zero, if bit 0 of CSR_EN and CSR_RELOAD are both set.

// Field: RELOAD0  Access: RW
// Reset: this field is not reset.
#define APU_TIMER_RELOAD0_LSB  0
#define APU_TIMER_RELOAD0_BITS 20
#define APU_TIMER_RELOAD0_MASK 0xfffff

/*******************************************************************************
*                                     CTR0                                     *
*******************************************************************************/

// Counter 0. Can be read and written by software. Counts down when bit 0 of
// CSR_EN is set. Raises IRQ 0 upon decrementing to 0.

// Field: CTR0  Access: RWV
// Reset: this field is not reset.
#define APU_TIMER_CTR0_LSB  0
#define APU_TIMER_CTR0_BITS 20
#define APU_TIMER_CTR0_MASK 0xfffff

/*******************************************************************************
*                                   RELOAD1                                    *
*******************************************************************************/

// Reload value for counter 1. The counter takes this value on the next tick
// after reaching zero, if bit 1 of CSR_EN and CSR_RELOAD are both set.

// Field: RELOAD1  Access: RW
// Reset: this field is not reset.
#define APU_TIMER_RELOAD1_LSB  0
#define APU_TIMER_RELOAD1_BITS 20
#define APU_TIMER_RELOAD1_MASK 0xfffff

/*******************************************************************************
*                                     CTR1                                     *
*******************************************************************************/

// Counter 1. Can be read and written by software. Counts down when bit 1 of
// CSR_EN is set. Raises IRQ 1 upon decrementing to 0.

// Field: CTR1  Access: RWV
// Reset: this field is not reset.
#define APU_TIMER_CTR1_LSB  0
#define APU_TIMER_CTR1_BITS 20
#define APU_TIMER_CTR1_MASK 0xfffff

/*******************************************************************************
*                                   RELOAD2                                    *
*******************************************************************************/

// Reload value for counter 2. The counter takes this value on the next tick
// after reaching zero, if bit 2 of CSR_EN and CSR_RELOAD are both set.

// Field: RELOAD2  Access: RW
// Reset: this field is not reset.
#define APU_TIMER_RELOAD2_LSB  0
#define APU_TIMER_RELOAD2_BITS 20
#define APU_TIMER_RELOAD2_MASK 0xfffff

/*******************************************************************************
*                                     CTR2                                     *
*******************************************************************************/

// Counter 2. Can be read and written by software. Counts down when bit 2 of
// CSR_EN is set. Raises IRQ 2 upon decrementing to 0.

// Field: CTR2  Access: RWV
// Reset: this field is not reset.
#define APU_TIMER_CTR2_LSB  0
#define APU_TIMER_CTR2_BITS 20
#define APU_TIMER_CTR2_MASK 0xfffff

#endif // _APU_TIMER_REGS_H_
