/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : apu_timer
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

module apu_timer_regs (
	input wire         clk,
	input wire         rst_n,
	
	// AHB-Lite Port
	input  wire [15:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output wire [31:0] ahbls_hrdata,
	output wire        ahbls_hresp,
	
	// Register interfaces
	output reg  [2:0]  csr_en_o,
	output reg  [2:0]  csr_reload_o,
	input  wire [2:0]  csr_irq_i,
	output reg  [2:0]  csr_irq_o,
	output reg  [7:0]  tick_o,
	output reg  [19:0] reload0_o,
	input  wire [19:0] ctr0_i,
	output reg  [19:0] ctr0_o,
	output reg         ctr0_wen,
	output reg  [19:0] reload1_o,
	input  wire [19:0] ctr1_i,
	output reg  [19:0] ctr1_o,
	output reg         ctr1_wen,
	output reg  [19:0] reload2_o,
	input  wire [19:0] ctr2_i,
	output reg  [19:0] ctr2_o,
	output reg         ctr2_wen
);

/* verilator lint_off UNUSEDSIGNAL */
// AHB-Lite adapter
wire [31:0] wdata = ahbls_hwdata;
reg         wen;
reg         ren;
reg  [15:0] addr;
always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 16'd0;
	end else if (ahbls_hready) begin
		wen <= ahbls_htrans[1] && ahbls_hwrite;
		ren <= ahbls_htrans[1] && !ahbls_hwrite;
		addr <= ahbls_haddr & 16'h1c;
	end
end

reg  [31:0] rdata;
assign ahbls_hrdata = rdata;
assign ahbls_hready_resp = 1'b1;
assign ahbls_hresp = 1'b0;

localparam ADDR_CSR = 0;
localparam ADDR_TICK = 4;
localparam ADDR_RELOAD0 = 8;
localparam ADDR_CTR0 = 12;
localparam ADDR_RELOAD1 = 16;
localparam ADDR_CTR1 = 20;
localparam ADDR_RELOAD2 = 24;
localparam ADDR_CTR2 = 28;

wire __csr_wen = wen && addr == ADDR_CSR;
wire __csr_ren = ren && addr == ADDR_CSR;
wire __tick_wen = wen && addr == ADDR_TICK;
wire __tick_ren = ren && addr == ADDR_TICK;
wire __reload0_wen = wen && addr == ADDR_RELOAD0;
wire __reload0_ren = ren && addr == ADDR_RELOAD0;
wire __ctr0_wen = wen && addr == ADDR_CTR0;
wire __ctr0_ren = ren && addr == ADDR_CTR0;
wire __reload1_wen = wen && addr == ADDR_RELOAD1;
wire __reload1_ren = ren && addr == ADDR_RELOAD1;
wire __ctr1_wen = wen && addr == ADDR_CTR1;
wire __ctr1_ren = ren && addr == ADDR_CTR1;
wire __reload2_wen = wen && addr == ADDR_RELOAD2;
wire __reload2_ren = ren && addr == ADDR_RELOAD2;
wire __ctr2_wen = wen && addr == ADDR_CTR2;
wire __ctr2_ren = ren && addr == ADDR_CTR2;

wire [2:0]  csr_en_wdata = wdata[2:0];
wire [2:0]  csr_en_rdata;
wire [2:0]  csr_reload_wdata = wdata[10:8];
wire [2:0]  csr_reload_rdata;
wire [2:0]  csr_irq_wdata = wdata[18:16];
wire [2:0]  csr_irq_rdata;
wire [31:0] __csr_rdata = {13'h0, csr_irq_rdata, 5'h0, csr_reload_rdata, 5'h0, csr_en_rdata};
assign csr_en_rdata = csr_en_o;
assign csr_reload_rdata = csr_reload_o;
reg [2:0]  csr_irq;
assign csr_irq_rdata = csr_irq;

wire [7:0]  tick_wdata = wdata[7:0];
wire [7:0]  tick_rdata;
wire [31:0] __tick_rdata = {24'h0, tick_rdata};
assign tick_rdata = tick_o;

wire [19:0] reload0_wdata = wdata[19:0];
wire [19:0] reload0_rdata;
wire [31:0] __reload0_rdata = {12'h0, reload0_rdata};
assign reload0_rdata = reload0_o;

wire [19:0] ctr0_wdata = wdata[19:0];
wire [19:0] ctr0_rdata;
wire [31:0] __ctr0_rdata = {12'h0, ctr0_rdata};
assign ctr0_rdata = ctr0_i;

wire [19:0] reload1_wdata = wdata[19:0];
wire [19:0] reload1_rdata;
wire [31:0] __reload1_rdata = {12'h0, reload1_rdata};
assign reload1_rdata = reload1_o;

wire [19:0] ctr1_wdata = wdata[19:0];
wire [19:0] ctr1_rdata;
wire [31:0] __ctr1_rdata = {12'h0, ctr1_rdata};
assign ctr1_rdata = ctr1_i;

wire [19:0] reload2_wdata = wdata[19:0];
wire [19:0] reload2_rdata;
wire [31:0] __reload2_rdata = {12'h0, reload2_rdata};
assign reload2_rdata = reload2_o;

wire [19:0] ctr2_wdata = wdata[19:0];
wire [19:0] ctr2_rdata;
wire [31:0] __ctr2_rdata = {12'h0, ctr2_rdata};
assign ctr2_rdata = ctr2_i;
/* verilator lint_on UNUSEDSIGNAL */

always @ (*) begin
	case (addr)
		ADDR_CSR: rdata = __csr_rdata;
		ADDR_TICK: rdata = __tick_rdata;
		ADDR_RELOAD0: rdata = __reload0_rdata;
		ADDR_CTR0: rdata = __ctr0_rdata;
		ADDR_RELOAD1: rdata = __reload1_rdata;
		ADDR_CTR1: rdata = __ctr1_rdata;
		ADDR_RELOAD2: rdata = __reload2_rdata;
		ADDR_CTR2: rdata = __ctr2_rdata;
		default: rdata = 32'h0;
	endcase
	csr_irq_o = csr_irq;
	ctr0_wen = __ctr0_wen;
	ctr0_o = ctr0_wdata;
	ctr1_wen = __ctr1_wen;
	ctr1_o = ctr1_wdata;
	ctr2_wen = __ctr2_wen;
	ctr2_o = ctr2_wdata;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		csr_en_o <= 3'h0;
		csr_reload_o <= 3'h0;
		csr_irq <= 3'h0;
		tick_o <= 8'h17;
	end else begin
		if (__csr_wen)
			csr_en_o <= csr_en_wdata;
		if (__csr_wen)
			csr_reload_o <= csr_reload_wdata;
		csr_irq <= (csr_irq & ~({3{__csr_wen}} & csr_irq_wdata)) | csr_irq_i;
		if (__tick_wen)
			tick_o <= tick_wdata;
	end
end

always @ (posedge clk) begin
	if (__reload0_wen)
		reload0_o <= reload0_wdata;
	if (__reload1_wen)
		reload1_o <= reload1_wdata;
	if (__reload2_wen)
		reload2_o <= reload2_wdata;
end

endmodule
