/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

// Block name           : apu_aout
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

module apu_aout_regs (
	input wire         clk,
	input wire         rst_n,
	
	// AHB-Lite Port
	input  wire [15:0] ahbls_haddr,
	input  wire [1:0]  ahbls_htrans,
	input  wire        ahbls_hwrite,
	input  wire [2:0]  ahbls_hsize,
	input  wire        ahbls_hready,
	output wire        ahbls_hready_resp,
	input  wire [31:0] ahbls_hwdata,
	output wire [31:0] ahbls_hrdata,
	output wire        ahbls_hresp,
	
	// Register interfaces
	input  wire        csr_rdy_i,
	output reg         csr_signed_o,
	input  wire        csr_running_i,
	output reg         csr_enable_o,
	output reg  [7:0]  csr_interval_o,
	output reg  [2:0]  csr_irqlevel_o,
	input  wire [2:0]  csr_flevel_i,
	output reg  [15:0] fifo_o,
	output reg         fifo_wen
);

/* verilator lint_off UNUSEDSIGNAL */
// AHB-Lite adapter
wire [31:0] wdata = ahbls_hwdata;
reg         wen;
reg         ren;
reg  [15:0] addr;
always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		wen <= 1'b0;
		ren <= 1'b0;
		addr <= 16'd0;
	end else if (ahbls_hready) begin
		wen <= ahbls_htrans[1] && ahbls_hwrite;
		ren <= ahbls_htrans[1] && !ahbls_hwrite;
		addr <= ahbls_haddr & 16'h4;
	end
end

reg  [31:0] rdata;
assign ahbls_hrdata = rdata;
assign ahbls_hready_resp = 1'b1;
assign ahbls_hresp = 1'b0;

localparam ADDR_CSR = 0;
localparam ADDR_FIFO = 4;

wire __csr_wen = wen && addr == ADDR_CSR;
wire __csr_ren = ren && addr == ADDR_CSR;
wire __fifo_wen = wen && addr == ADDR_FIFO;
wire __fifo_ren = ren && addr == ADDR_FIFO;

wire        csr_rdy_wdata = wdata[31];
wire        csr_rdy_rdata;
wire        csr_signed_wdata = wdata[24];
wire        csr_signed_rdata;
wire        csr_running_wdata = wdata[17];
wire        csr_running_rdata;
wire        csr_enable_wdata = wdata[16];
wire        csr_enable_rdata;
wire [7:0]  csr_interval_wdata = wdata[15:8];
wire [7:0]  csr_interval_rdata;
wire [2:0]  csr_irqlevel_wdata = wdata[6:4];
wire [2:0]  csr_irqlevel_rdata;
wire [2:0]  csr_flevel_wdata = wdata[2:0];
wire [2:0]  csr_flevel_rdata;
wire [31:0] __csr_rdata = {csr_rdy_rdata, 6'h0, csr_signed_rdata, 6'h0, csr_running_rdata, csr_enable_rdata, csr_interval_rdata, 1'h0, csr_irqlevel_rdata, 1'h0, csr_flevel_rdata};
assign csr_rdy_rdata = csr_rdy_i;
assign csr_signed_rdata = csr_signed_o;
assign csr_running_rdata = csr_running_i;
assign csr_enable_rdata = csr_enable_o;
assign csr_interval_rdata = csr_interval_o;
assign csr_irqlevel_rdata = csr_irqlevel_o;
assign csr_flevel_rdata = csr_flevel_i;

wire [15:0] fifo_wdata = wdata[15:0];
wire [15:0] fifo_rdata;
wire [31:0] __fifo_rdata = {16'h0, fifo_rdata};
assign fifo_rdata = 16'h0;
/* verilator lint_on UNUSEDSIGNAL */

always @ (*) begin
	case (addr)
		ADDR_CSR: rdata = __csr_rdata;
		ADDR_FIFO: rdata = __fifo_rdata;
		default: rdata = 32'h0;
	endcase
	fifo_wen = __fifo_wen;
	fifo_o = fifo_wdata;
end

always @ (posedge clk or negedge rst_n) begin
	if (!rst_n) begin
		csr_signed_o <= 1'h0;
		csr_enable_o <= 1'h0;
		csr_interval_o <= 8'h79;
		csr_irqlevel_o <= 3'h2;
	end else begin
		if (__csr_wen)
			csr_signed_o <= csr_signed_wdata;
		if (__csr_wen)
			csr_enable_o <= csr_enable_wdata;
		if (__csr_wen)
			csr_interval_o <= csr_interval_wdata;
		if (__csr_wen)
			csr_irqlevel_o <= csr_irqlevel_wdata;
	end
end

endmodule
