/*******************************************************************************
*                          AUTOGENERATED BY REGBLOCK                           *
*                            Do not edit manually.                             *
*          Edit the source file (or regblock utility) and regenerate.          *
*******************************************************************************/

#ifndef _APU_AOUT_REGS_H_
#define _APU_AOUT_REGS_H_

// Block name           : apu_aout
// Bus type             : ahbl
// Bus data width       : 32
// Bus address width    : 16

#define APU_AOUT_CSR_OFFS 0
#define APU_AOUT_FIFO_OFFS 4

#ifndef __ASSEMBLER__
#include <stdint.h>

typedef struct {
	volatile uint32_t csr;
	volatile uint32_t fifo;
} apu_aout_hw_t;

#endif // !__ASSEMBLER__


/*******************************************************************************
*                                     CSR                                      *
*******************************************************************************/

// Field: CSR_RDY  Access: ROV
// Reset: 0x0
// Returns 1 when the sample FIFO is ready to accept more data
#define APU_AOUT_CSR_RDY_LSB  31
#define APU_AOUT_CSR_RDY_BITS 1
#define APU_AOUT_CSR_RDY_MASK 0x80000000
// Field: CSR_SIGNED  Access: RW
// Reset: 0x0
// APU audio is natively unsigned. This bit is XORed into bit 15 of each sample
// to map signed samples to the correct range.
#define APU_AOUT_CSR_SIGNED_LSB  24
#define APU_AOUT_CSR_SIGNED_BITS 1
#define APU_AOUT_CSR_SIGNED_MASK 0x1000000
// Field: CSR_RUNNING  Access: ROV
// Reset: 0x0
// Whether the audio output is currently running. Poll after changing ENABLE
// before changing INTERVAL.
#define APU_AOUT_CSR_RUNNING_LSB  17
#define APU_AOUT_CSR_RUNNING_BITS 1
#define APU_AOUT_CSR_RUNNING_MASK 0x20000
// Field: CSR_ENABLE  Access: RW
// Reset: 0x0
// Enable the audio output
#define APU_AOUT_CSR_ENABLE_LSB  16
#define APU_AOUT_CSR_ENABLE_BITS 1
#define APU_AOUT_CSR_ENABLE_MASK 0x10000
// Field: CSR_INTERVAL  Access: RW
// Reset: 0x7b
// Sample period in audio clock cycles is 4 x (INTERVAL + 2). Nominal value of
// 123 yields 48 kSa/s with a 22 kHz cutoff on the upsampling filter, from a 24
// MHz audio clock.
#define APU_AOUT_CSR_INTERVAL_LSB  8
#define APU_AOUT_CSR_INTERVAL_BITS 8
#define APU_AOUT_CSR_INTERVAL_MASK 0xff00
// Field: CSR_IRQLEVEL  Access: RW
// Reset: 0x2
// IRQ is asserted when FIFO level is less than or equal to IRQLEVEL.
#define APU_AOUT_CSR_IRQLEVEL_LSB  4
#define APU_AOUT_CSR_IRQLEVEL_BITS 3
#define APU_AOUT_CSR_IRQLEVEL_MASK 0x70
// Field: CSR_FLEVEL  Access: ROV
// Reset: 0x0
// Returns the current occupancy of the sample FIFO (4 x 32-bit).
#define APU_AOUT_CSR_FLEVEL_LSB  0
#define APU_AOUT_CSR_FLEVEL_BITS 3
#define APU_AOUT_CSR_FLEVEL_MASK 0x7

/*******************************************************************************
*                                     FIFO                                     *
*******************************************************************************/

// Field: FIFO_L  Access: WF
// Reset: 0x0
// Left audio sample
#define APU_AOUT_FIFO_L_LSB  16
#define APU_AOUT_FIFO_L_BITS 16
#define APU_AOUT_FIFO_L_MASK 0xffff0000
// Field: FIFO_R  Access: WF
// Reset: 0x0
// Right audio sample
#define APU_AOUT_FIFO_R_LSB  0
#define APU_AOUT_FIFO_R_BITS 16
#define APU_AOUT_FIFO_R_MASK 0xffff

#endif // _APU_AOUT_REGS_H_
